/* medius C ABI. See https://github.com/K4HVH/medius. MIT. */

#ifndef MEDIUS_H
#define MEDIUS_H

#pragma once

/* Generated by tools/gen-header.sh (cbindgen). Do not edit by hand. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Largest number of held usages in one catch snapshot.
#define MEDIUS_MAX_USAGES 256

// Largest number of entries in a decoded `RESP(LOCKS)`.
#define MEDIUS_MAX_LOCKS 256

// Capacity for a log line's text (the wire payload is at most 512 bytes).
#define MEDIUS_MAX_LOG_TEXT 512

// Capacity for a discovered serial-port path.
#define MEDIUS_MAX_PATH 512

// Capacity for a cloned device's product string (the wire caps it at 127 bytes).
#define MEDIUS_MAX_PRODUCT 128

// Capacity for the box name string (the wire caps it at 32 bytes; +1 for the NUL terminator).
#define MEDIUS_MAX_NAME 33

// Capacity for a control adapter's serial string.
#define MEDIUS_MAX_SERIAL 128

// Largest CATCH subscription table the box holds (the firmware `CTRL_CATCH_MAXN`).
#define MEDIUS_MAX_CATCH_ENTRIES 32

// Largest traffic payload one event carries (the firmware `CTRL_TRAFFIC_DATA_MAX`).
#define MEDIUS_MAX_TRAFFIC_BYTES 180

// CATCH classes, the `class` of a `MediusCatchFilter`. 0-3 are the classes `LOCK` and `INJECT`
// address; 4-10 are the traffic the box relays.
#define MEDIUS_CATCH_CLASS_BTN 0

#define MEDIUS_CATCH_CLASS_KEY 1

#define MEDIUS_CATCH_CLASS_MEDIA 2

#define MEDIUS_CATCH_CLASS_AXIS 3

// Raw HID input report bytes, keyed by interface number.
#define MEDIUS_CATCH_CLASS_HID_IN 4

// Interrupt-OUT report bytes the PC wrote, keyed by endpoint address.
#define MEDIUS_CATCH_CLASS_HID_OUT 5

// Vendor-interface interrupt traffic, keyed by endpoint address.
#define MEDIUS_CATCH_CLASS_VENDOR_INTERRUPT 6

// Vendor-interface bulk traffic, keyed by endpoint address.
#define MEDIUS_CATCH_CLASS_VENDOR_BULK 7

// A proxied control transaction, keyed by endpoint number (0 = EP0).
#define MEDIUS_CATCH_CLASS_CONTROL 8

// The bytes the clone put on the wire, keyed by endpoint address.
#define MEDIUS_CATCH_CLASS_EMIT 9

// Bus lifecycle: reset, suspend, configuration and interface changes, attach and detach.
#define MEDIUS_CATCH_CLASS_BUS 10

// Wildcard: every class.
#define MEDIUS_CATCH_CLASS_ANY 255

// Wildcard: every id within a class.
#define MEDIUS_CATCH_ID_ANY 65535

// `MediusClockEstimate::age_ms` when the box has no estimate yet.
#define MEDIUS_CLOCK_AGE_NONE UINT32_MAX

// `MediusClockEstimate::rate_ppb` when the box has fitted no drift rate.
#define MEDIUS_CLOCK_RATE_NONE INT32_MIN

// `LOCK` scale: percent of the physical value kept. 0 blocks, 100 passes it untouched, above 100
// amplifies, to 255 (2.55x).
#define MEDIUS_LOCK_SCALE_BLOCK 0

#define MEDIUS_LOCK_SCALE_PASS 100

#define MEDIUS_LOCK_SCALE_MAX 255

// The bearing window the box holds before any host sets one, in ms.
#define MEDIUS_BEARING_WINDOW_DEFAULT_MS 20

// The max clip trigger bindings in a `MediusClipSettings` (matches the firmware `CLIP_TRIG_MAX`).
#define MEDIUS_CLIP_TRIG_MAX 8

// The result of a fallible `medius_*` call. `MEDIUS_OK` is zero; everything else is a failure.
enum MediusStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_STATUS_OK = 0,
    MEDIUS_STATUS_ERR_IO = 1,
    MEDIUS_STATUS_ERR_NOT_FOUND = 2,
    MEDIUS_STATUS_ERR_NO_REPLY = 3,
    MEDIUS_STATUS_ERR_BAD_PROTO_VER = 4,
    MEDIUS_STATUS_ERR_QUERY_TIMEOUT = 5,
    MEDIUS_STATUS_ERR_DISCONNECTED = 6,
    MEDIUS_STATUS_ERR_FRAME_TOO_LONG = 7,
    MEDIUS_STATUS_ERR_UPDATE = 8,
    MEDIUS_STATUS_ERR_INVALID_ARG = 9,
    MEDIUS_STATUS_ERR_PANIC = 10,
    MEDIUS_STATUS_ERR_UNKNOWN = 11,
    // The subscription needs more entries than the box's table holds.
    MEDIUS_STATUS_ERR_CATCH_TABLE_FULL = 12,
    // A catch subscription with no filters, which would never yield an event.
    MEDIUS_STATUS_ERR_EMPTY_SUBSCRIPTION = 13,
    // A non-zero `capture` on an input class, which carries no packet.
    MEDIUS_STATUS_ERR_CAPTURE_NOT_APPLICABLE = 14,
    // A traffic class passed to `medius_device_input_events`, which cannot decode one.
    MEDIUS_STATUS_ERR_NOT_AN_INPUT_FILTER = 15,
    // The everything filter passed to `medius_device_input_events`; it covers traffic too.
    MEDIUS_STATUS_ERR_WILDCARD_NOT_INPUT = 16,
    // An input filter narrowed to one edge, which cannot be decoded into press and release.
    MEDIUS_STATUS_ERR_HALF_EDGE_INPUT_FILTER = 17,
    // An exact id equal to the blanket sentinel, which would address the whole class.
    MEDIUS_STATUS_ERR_RESERVED_ID = 18,
    // `MEDIUS_DIRECTION_WITH` / `_AGAINST` on something with no bearing to measure them against.
    MEDIUS_STATUS_ERR_RELATIVE_DIRECTION = 19,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusStatus MediusStatus;
#else
typedef int32_t MediusStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// How the box decides whether physical motion runs with or against its own injection.
enum MediusBearingMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // Each axis compares its own sign against its own bearing, independently.
    MEDIUS_BEARING_MODE_PER_AXIS = 0,
    // The physical delta is projected onto the injected XY vector. One
    // relative scale governs both axes, the lower of X's and Y's, and that is what reads back.
    // Each axis's absolute scale then applies to what the projection left, not to the sign the report
    // carried: it governs what reaches the PC.
    MEDIUS_BEARING_MODE_VECTOR = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusBearingMode MediusBearingMode;
#else
typedef uint8_t MediusBearingMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What paces injected motion.
enum MediusEmitMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_EMIT_MODE_LEARNED = 0,
    MEDIUS_EMIT_MODE_INTERVAL = 1,
    MEDIUS_EMIT_MODE_FIXED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusEmitMode MediusEmitMode;
#else
typedef uint8_t MediusEmitMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What the real device answered a proxied control transaction with.
enum MediusControlStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_CONTROL_STATUS_OK = 0,
    MEDIUS_CONTROL_STATUS_STALLED = 1,
    MEDIUS_CONTROL_STATUS_NAKED = 2,
    // A status byte this build does not know. Read `MediusTrafficEvent::flags` for its value. Kept
    // distinct rather than folded into the nearest known one: a catch-all arm reported a future
    // firmware's new status as a timeout, which reads as a device fault that never happened.
    MEDIUS_CONTROL_STATUS_OTHER = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusControlStatus MediusControlStatus;
#else
typedef uint8_t MediusControlStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What a `MEDIUS_CATCH_CLASS_BUS` event describes.
enum MediusBusEventKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_BUS_EVENT_KIND_RESET = 0,
    MEDIUS_BUS_EVENT_KIND_SUSPEND = 1,
    MEDIUS_BUS_EVENT_KIND_RESUME = 2,
    // `SET_CONFIGURATION` selected `configuration`.
    MEDIUS_BUS_EVENT_KIND_CONFIGURED = 3,
    MEDIUS_BUS_EVENT_KIND_DECONFIGURED = 4,
    // `SET_INTERFACE` selected `alt` on `interface`.
    MEDIUS_BUS_EVENT_KIND_SET_INTERFACE = 5,
    MEDIUS_BUS_EVENT_KIND_DEVICE_ATTACHED = 6,
    MEDIUS_BUS_EVENT_KIND_DEVICE_DETACHED = 7,
    MEDIUS_BUS_EVENT_KIND_CLONE_UP = 8,
    MEDIUS_BUS_EVENT_KIND_CLONE_DOWN = 9,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusBusEventKind MediusBusEventKind;
#else
typedef uint8_t MediusBusEventKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which arm of a [`MediusCatchEvent`] is populated.
enum MediusCatchEventKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // A relative-axis event (`data.motion`).
    MEDIUS_CATCH_EVENT_KIND_MOTION = 0,
    // A held-usage snapshot for one class (`data.usages`).
    MEDIUS_CATCH_EVENT_KIND_USAGES = 1,
    // Byte-oriented traffic (`data.traffic`).
    MEDIUS_CATCH_EVENT_KIND_TRAFFIC = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusCatchEventKind MediusCatchEventKind;
#else
typedef uint8_t MediusCatchEventKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which chip's clock stamped an event.
//
// The two chips boot independently, so nothing relates their timers: a stamp is only meaningful
// against another from the same domain. To place both on one timeline, apply
// `MediusClockEstimate::offset_us` and respect its error bound.
enum MediusClockDomain
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // The device-facing chip: everything the real device produced.
    MEDIUS_CLOCK_DOMAIN_HOST_CHIP = 0,
    // The PC-facing chip: everything the PC produced and everything the clone emitted.
    MEDIUS_CLOCK_DOMAIN_DEVICE_CHIP = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusClockDomain MediusClockDomain;
#else
typedef uint8_t MediusClockDomain;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which arm of a [`MediusInputEvent`] is populated.
enum MediusInputKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // A momentary usage went down; read `usage`.
    MEDIUS_INPUT_KIND_PRESS = 0,
    // A momentary usage came up; read `usage`.
    MEDIUS_INPUT_KIND_RELEASE = 1,
    // A relative-motion report; read `dx`/`dy`/`dz`.
    MEDIUS_INPUT_KIND_MOTION = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusInputKind MediusInputKind;
#else
typedef uint8_t MediusInputKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A device log line's severity.
enum MediusLogLevel
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LOG_LEVEL_ERROR = 0,
    MEDIUS_LOG_LEVEL_WARN = 1,
    MEDIUS_LOG_LEVEL_INFO = 2,
    MEDIUS_LOG_LEVEL_DEBUG = 3,
    MEDIUS_LOG_LEVEL_VERBOSE = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLogLevel MediusLogLevel;
#else
typedef uint8_t MediusLogLevel;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A wire frame type (the `TYPE` byte). Used with the mock recorder.
enum MediusFrameType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_FRAME_TYPE_MOVE = 1,
    MEDIUS_FRAME_TYPE_INJECT = 3,
    MEDIUS_FRAME_TYPE_RESET = 4,
    MEDIUS_FRAME_TYPE_QUERY = 5,
    MEDIUS_FRAME_TYPE_RESP = 6,
    MEDIUS_FRAME_TYPE_REBOOT_DL = 7,
    MEDIUS_FRAME_TYPE_LOG = 8,
    MEDIUS_FRAME_TYPE_LED = 9,
    MEDIUS_FRAME_TYPE_LOCK = 10,
    MEDIUS_FRAME_TYPE_CATCH = 11,
    MEDIUS_FRAME_TYPE_MOTION_EVENT = 12,
    MEDIUS_FRAME_TYPE_USAGE_EVENT = 15,
    MEDIUS_FRAME_TYPE_TRAFFIC_EVENT = 22,
    MEDIUS_FRAME_TYPE_OPTION = 17,
    MEDIUS_FRAME_TYPE_CLIP_APPEND = 18,
    MEDIUS_FRAME_TYPE_CLIP_CTRL = 19,
    MEDIUS_FRAME_TYPE_CLIP_SET = 20,
    MEDIUS_FRAME_TYPE_CLIP_TRIGGER = 21,
    MEDIUS_FRAME_TYPE_UPDATE = 23,
    MEDIUS_FRAME_TYPE_UPDATE_RESP = 24,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusFrameType MediusFrameType;
#else
typedef uint8_t MediusFrameType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// An injection override action.
enum MediusAction
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_ACTION_SOFT_RELEASE = 0,
    MEDIUS_ACTION_PRESS = 1,
    MEDIUS_ACTION_FORCE_RELEASE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusAction MediusAction;
#else
typedef uint8_t MediusAction;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A relative axis. Values match the wire axis id a `CATCH` or `LOCK` entry carries.
enum MediusAxis
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_AXIS_X = 0,
    MEDIUS_AXIS_Y = 1,
    MEDIUS_AXIS_WHEEL = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusAxis MediusAxis;
#else
typedef uint8_t MediusAxis;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A whole input group for a blanket lock or a clip auto-lock scope.
enum MediusBlanket
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_BLANKET_AIM = 0,
    MEDIUS_BLANKET_WHEEL = 1,
    MEDIUS_BLANKET_BUTTONS = 2,
    MEDIUS_BLANKET_KEYS = 3,
    MEDIUS_BLANKET_MEDIA = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusBlanket MediusBlanket;
#else
typedef uint8_t MediusBlanket;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A mouse button. Values match the firmware button id.
enum MediusButton
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_BUTTON_LEFT = 0,
    MEDIUS_BUTTON_RIGHT = 1,
    MEDIUS_BUTTON_MIDDLE = 2,
    MEDIUS_BUTTON_SIDE1 = 3,
    MEDIUS_BUTTON_SIDE2 = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusButton MediusButton;
#else
typedef uint8_t MediusButton;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// The class of a [`MediusUsage`] (button / key / media).
enum MediusClass
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_CLASS_BUTTON = 0,
    MEDIUS_CLASS_KEY = 1,
    MEDIUS_CLASS_MEDIA = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusClass MediusClass;
#else
typedef uint8_t MediusClass;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// The engine action a trigger binding drives.
enum MediusClipAction
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_CLIP_ACTION_START = 0,
    MEDIUS_CLIP_ACTION_STOP = 1,
    MEDIUS_CLIP_ACTION_PAUSE = 2,
    MEDIUS_CLIP_ACTION_RESUME = 3,
    MEDIUS_CLIP_ACTION_RESTART = 4,
    MEDIUS_CLIP_ACTION_TOGGLE = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusClipAction MediusClipAction;
#else
typedef uint8_t MediusClipAction;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// The device-side clip lifecycle state (`medius_clip_query_status`).
enum MediusClipState
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // No clip playing (empty, or a loaded clip parked at its start).
    MEDIUS_CLIP_STATE_IDLE = 0,
    // Draining the ring, one entry per native frame.
    MEDIUS_CLIP_STATE_PLAYING = 1,
    // Halted mid-clip; the cursor and any held usages are retained.
    MEDIUS_CLIP_STATE_PAUSED = 2,
    // An append was dropped or the ring overflowed; recover with `medius_clip_clear`.
    MEDIUS_CLIP_STATE_FAULTED = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusClipState MediusClipState;
#else
typedef uint8_t MediusClipState;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// The cloned device's primary kind, from its Boot-interface protocol.
enum MediusDeviceKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_DEVICE_KIND_UNKNOWN = 0,
    MEDIUS_DEVICE_KIND_KEYBOARD = 1,
    MEDIUS_DEVICE_KIND_MOUSE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusDeviceKind MediusDeviceKind;
#else
typedef uint8_t MediusDeviceKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which edge of an axis/button a lock applies to.
enum MediusDirection
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // Both edges, both signs, or both flows; on a `LOCK` scale the two fixed signs, with the
    // relative pair passing.
    MEDIUS_DIRECTION_BOTH = 0,
    MEDIUS_DIRECTION_POSITIVE = 1,
    MEDIUS_DIRECTION_NEGATIVE = 2,
    // The axis sign the box is currently injecting. Measured against the bearing, so the sign it covers follows the
    // injection rather than the axis; inert while no bearing is live. Axes only.
    MEDIUS_DIRECTION_WITH = 3,
    // The axis sign opposing the box's injection. Measured against the bearing; axes only.
    MEDIUS_DIRECTION_AGAINST = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusDirection MediusDirection;
#else
typedef uint8_t MediusDirection;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which edge of a trigger usage fires its binding (matches the lock direction wire values).
enum MediusEdge
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_EDGE_BOTH = 0,
    MEDIUS_EDGE_PRESS = 1,
    MEDIUS_EDGE_RELEASE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusEdge MediusEdge;
#else
typedef uint8_t MediusEdge;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// LED drive mode.
enum MediusLedMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LED_MODE_AUTO = 0,
    MEDIUS_LED_MODE_OFF = 1,
    MEDIUS_LED_MODE_SOLID = 2,
    MEDIUS_LED_MODE_BLINK = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLedMode MediusLedMode;
#else
typedef uint8_t MediusLedMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which status LED a command addresses.
enum MediusLedTarget
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LED_TARGET_DEVICE = 0,
    MEDIUS_LED_TARGET_HOST = 1,
    MEDIUS_LED_TARGET_BOTH = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLedTarget MediusLedTarget;
#else
typedef uint8_t MediusLedTarget;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What a lock addresses: a relative axis, or a momentary usage (button/key/media).
enum MediusLockTargetKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // The X cursor axis.
    MEDIUS_LOCK_TARGET_KIND_X = 0,
    // The Y cursor axis.
    MEDIUS_LOCK_TARGET_KIND_Y = 1,
    // The wheel.
    MEDIUS_LOCK_TARGET_KIND_WHEEL = 2,
    // A momentary usage; read `usage`.
    MEDIUS_LOCK_TARGET_KIND_USAGE = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLockTargetKind MediusLockTargetKind;
#else
typedef uint8_t MediusLockTargetKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which arm of a [`MediusMotion`] is populated.
enum MediusMotionKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_MOTION_KIND_CURSOR = 0,
    MEDIUS_MOTION_KIND_WHEEL = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusMotionKind MediusMotionKind;
#else
typedef uint8_t MediusMotionKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// When a delta reaches the game PC, against movement riding.
enum MediusMoveTiming
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_MOVE_TIMING_RIDE = 0,
    MEDIUS_MOVE_TIMING_NOW = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusMoveTiming MediusMoveTiming;
#else
typedef uint8_t MediusMoveTiming;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What a move does to the motion already held for a ride.
enum MediusPendingMotion
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_PENDING_MOTION_KEEP = 0,
    MEDIUS_PENDING_MOTION_FLUSH = 1,
    MEDIUS_PENDING_MOTION_DISCARD = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusPendingMotion MediusPendingMotion;
#else
typedef uint8_t MediusPendingMotion;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A reboot target chip + mode.
enum MediusRebootTarget
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_REBOOT_TARGET_DEVICE_DOWNLOAD = 0,
    MEDIUS_REBOOT_TARGET_HOST_DOWNLOAD = 1,
    MEDIUS_REBOOT_TARGET_DEVICE_RUN = 2,
    MEDIUS_REBOOT_TARGET_HOST_RUN = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusRebootTarget MediusRebootTarget;
#else
typedef uint8_t MediusRebootTarget;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A handle to one box's buffered-clip playback (owns the append-sequence counter, one per session).
typedef struct MediusClip MediusClip;

// An opaque builder for a clip entry stream.
typedef struct MediusClipBuilder MediusClipBuilder;

// An open connection to one medius box; create with `medius_device_open`/`_find` and free with `medius_device_free`.
typedef struct MediusDevice MediusDevice;

// A live CATCH event stream; create with `medius_device_catch_events`, free with `medius_event_stream_free`.
typedef struct MediusEventStream MediusEventStream;

// A live decoded-input stream; create with `medius_device_input_events`, free with
// `medius_input_stream_free`. Not clonable: it holds the per-class held sets it diffs.
typedef struct MediusInputStream MediusInputStream;

// A device LOG stream. Opaque; create with `medius_device_logs`, release with `medius_log_stream_free`.
typedef struct MediusLogStream MediusLogStream;

#if defined(MEDIUS_FEATURE_MOCK)
// A scriptable fake box. Opaque; create with `medius_mock_new`, free with `medius_mock_free`.
typedef struct MediusMockBox MediusMockBox;
#endif

// A host-side clock mapping; create with `medius_timeline_new`, free with `medius_timeline_free`.
//
// A catch stamp is microseconds on a chip that booted before this process did: it wraps every ~71.6
// minutes and has no relation to any clock here. Feed every event in as it arrives, in order,
// passing your own monotonic `now_ns`.
typedef struct MediusTimeline MediusTimeline;

// A momentary usage for `medius_device_inject`; build with the `medius_usage_*` helpers.
typedef struct MediusUsage {
    // A `MEDIUS_CLASS_*` value.
    uint8_t kind;
    uint16_t id;
} MediusUsage;

// One clip trigger binding: `on`'s `edge` drives `action`; `consume` suppresses the input from the game.
typedef struct MediusClipTrigger {
    struct MediusUsage on;
    // A `MEDIUS_EDGE_*` value.
    uint8_t edge;
    // A `MEDIUS_CLIP_ACTION_*` value.
    uint8_t action;
    uint8_t consume;
} MediusClipTrigger;

// A snapshot of the device-side clip ring and playback counters (the runtime view of `RESP(CLIP)`).
typedef struct MediusClipStatus {
    // A `MEDIUS_CLIP_STATE_*` value.
    uint8_t state;
    uint32_t free;
    // The retained clip size in bytes (streaming: buffered-but-undrained bytes).
    uint32_t total;
    // Bytes played from the clip start (retained progress; ~0 while streaming).
    uint32_t played;
    uint32_t ticks;
    uint16_t underruns;
    uint16_t overruns;
    uint16_t seq_gaps;
    uint16_t held_n;
    struct MediusUsage held[MEDIUS_MAX_USAGES];
} MediusClipStatus;

// The clip configuration read back from `RESP(CLIP)`: autolock scope, loop/retain scalars, and triggers.
typedef struct MediusClipSettings {
    // The autolock scope as `CLIP_LOCK_*` bits (`medius_clip_set_autolock`).
    uint8_t autolock_bits;
    uint8_t loop_;
    uint8_t retain;
    uint8_t finalized;
    // Whether the clip's motion waits to ride a native report (`medius_clip_set_ride`).
    uint8_t ride;
    struct MediusClipTrigger triggers[MEDIUS_CLIP_TRIG_MAX];
    // The number of valid entries in `triggers`.
    uint8_t n;
} MediusClipSettings;

// A discovered medius serial port. `path` is NUL-terminated.
typedef struct MediusPortInfo {
    char path[MEDIUS_MAX_PATH];
    uint16_t vid;
    uint16_t pid;
    // The control adapter's serial (NUL-terminated); empty and `has_serial == 0` when it serves none.
    char serial[MEDIUS_MAX_SERIAL];
    uint8_t has_serial;
} MediusPortInfo;

// Decoded firmware version; `mac` is the device chip's base MAC, a stable per-box identity.
typedef struct MediusVersion {
    uint8_t proto_ver;
    uint8_t fw_major;
    uint8_t fw_minor;
    uint8_t fw_patch;
    uint8_t mac[6];
    char name[MEDIUS_MAX_NAME];
} MediusVersion;

// The cloned device's USB identity, primary kind, and product string.
typedef struct MediusDeviceInfo {
    uint16_t vid;
    uint16_t pid;
    uint16_t bcd_device;
    uint16_t bcd_usb;
    uint8_t has_serial;
    uint8_t has_bos;
    // A `MEDIUS_DEVICE_KIND_*` value.
    uint8_t kind;
    char product[MEDIUS_MAX_PRODUCT];
} MediusDeviceInfo;

// One discovered box: its control port, firmware version (with the box MAC), and the device it clones.
typedef struct MediusBoxInfo {
    struct MediusPortInfo port;
    struct MediusVersion version;
    struct MediusDeviceInfo device;
} MediusBoxInfo;

// A relative-axis drive for `medius_device_move_axis`; build with the `medius_motion_*` helpers.
typedef struct MediusMotion {
    // A `MEDIUS_MOTION_KIND_*` value.
    uint8_t kind;
    int16_t dx;
    int16_t dy;
    int16_t wheel;
} MediusMotion;

// A lock target: an axis (`kind` is `X`/`Y`/`Wheel`) or a momentary usage (`kind` is `Usage`, read `usage`).
typedef struct MediusLockTarget {
    // A `MEDIUS_LOCK_TARGET_KIND_*` value.
    uint8_t kind;
    struct MediusUsage usage;
} MediusLockTarget;

// One chip's firmware version and which of its two app slots it booted.
typedef struct MediusChipFirmware {
    uint8_t major;
    uint8_t minor;
    uint8_t patch;
    // 0 = ota_0, 1 = ota_1.
    uint8_t slot;
    // 0 new, 1 pending-verify, 2 valid, 3 invalid, 4 aborted, 0xFF unknown.
    uint8_t state;
} MediusChipFirmware;

// Both chips' firmware state (`RESP(FIRMWARE)`).
typedef struct MediusFirmwareInfo {
    struct MediusChipFirmware device;
    // 0 when the host chip has not answered over the inter-chip link; `host` is then meaningless.
    uint8_t host_present;
    struct MediusChipFirmware host;
    // Usable bytes in a spare slot; the same on both chips.
    uint32_t slot_size;
    uint8_t device_staged;
    uint8_t host_staged;
} MediusFirmwareInfo;

// Box health flags (each field is 0 or 1).
typedef struct MediusHealth {
    uint8_t link_up;
    uint8_t mouse_attached;
    uint8_t clone_configured;
    uint8_t injection_active;
    uint8_t rate_confident;
    uint8_t lock_on;
    uint8_t catch_on;
    uint8_t kbd_attached;
} MediusHealth;

// Mouse half of the cloned device's capabilities.
typedef struct MediusMouseCaps {
    uint8_t n_buttons;
    uint8_t has_x;
    uint8_t has_y;
    uint8_t has_wheel;
    uint8_t has_report_id;
    uint8_t n_hid;
} MediusMouseCaps;

// Keyboard half of the cloned device's capabilities. `n_keys == 0xFF` signals an NKRO bitmap.
typedef struct MediusKbdCaps {
    uint8_t n_keys;
    uint8_t nkro;
    uint8_t has_consumer;
    uint8_t has_system;
    uint8_t has_report_id;
} MediusKbdCaps;

// The whole cloned device's capabilities.
typedef struct MediusCaps {
    struct MediusMouseCaps mouse;
    struct MediusKbdCaps keyboard;
    uint8_t mouse_change_driven;
    uint8_t kbd_change_driven;
} MediusCaps;

// The live native report rate and clone poll period.
typedef struct MediusRate {
    uint16_t native_period_us;
    uint16_t poll_period_us;
    uint8_t confident;
    uint8_t change_driven;
} MediusRate;

// Box-side delivery/telemetry counters.
typedef struct MediusStats {
    uint32_t inject_emits;
    uint16_t tx_drops;
    uint16_t tx_merges;
    uint8_t tx_maxdepth;
    uint8_t tx_wedges;
    uint16_t wakeups;
    uint16_t reset_count;
    uint16_t config_count;
} MediusStats;

// One entry in a decoded `RESP(LOCKS)`: the locked target and which edges are locked.
typedef struct MediusLockEntry {
    struct MediusLockTarget target;
    bool is_blanket;
    // A `MEDIUS_DIRECTION_*` value: which direction of the target this entry weighs.
    // A byte rather than `MediusDirection`, so the boundary can validate it before anything reads it
    // as one; C++ renders the enum as `enum : uint8_t`, so assigning this to a `MediusDirection`
    // there needs a cast.
    uint8_t direction;
    // Percent of the physical value kept: 0 blocks, 100 passes, above 100 amplifies. A momentary
    // usage carries one bit, so the box stores the block or pass it renders and one never reports a
    // value in between.
    //
    // This is the figure the box applies, not the byte it was sent: in `MEDIUS_BEARING_MODE_VECTOR`
    // one relative scale governs the whole aim, the lower of X's and Y's, and both relative entries
    // carry that number.
    uint8_t scale;
} MediusLockEntry;

// The active locks: `entries[0..n]`. Use `medius_locks_is_locked` to test a target/direction.
typedef struct MediusLocks {
    uint16_t n;
    struct MediusLockEntry entries[MEDIUS_MAX_LOCKS];
} MediusLocks;

// The measured difference between the two chips' clocks, from `RESP(CATCH)`.
typedef struct MediusClockEstimate {
    // The host chip's clock minus the device chip's, in microseconds.
    int32_t offset_us;
    // Relative drift between the two crystals in parts per billion, or `MEDIUS_CLOCK_RATE_NONE`
    // when the box has fitted none. That is a different answer from a fitted 0, which says the two
    // crystals match: on a link too busy for enough clean exchanges no fit is made at all, which is
    // exactly when assuming no drift is least safe.
    int32_t rate_ppb;
    // Best measured round trip in the window. The offset is good to about half of this.
    uint16_t delay_us;
    // Age of the estimate, or `MEDIUS_CLOCK_AGE_NONE` when the box has no estimate yet. The
    // sentinel is load-bearing: an offset that was never measured also reads as zero, and applying
    // it would silently shift every cross-domain stamp.
    uint32_t age_ms;
} MediusClockEstimate;

// A CATCH class, one of the `MEDIUS_CATCH_CLASS_*` values.
typedef uint8_t MediusCatchClass;

// One CATCH subscription entry: what to observe, in which direction, and how much of each packet to
// keep. Build one with a `medius_catch_filter_*` helper.
//
// The box resolves each event to its most specific matching entry -- an exact `(class, id)` beats a
// class blanket, which beats the everything filter, and a named direction beats `Both` -- and that
// entry supplies `capture`. The wildcards are sentinels rather than a separate flag:
// `class = MEDIUS_CATCH_CLASS_ANY` matches every class and `id = MEDIUS_CATCH_ID_ANY` every id
// within one. The wildcard class with a real id addresses nothing and is refused.
typedef struct MediusCatchFilter {
    // One of `MEDIUS_CATCH_CLASS_*`, or `MEDIUS_CATCH_CLASS_ANY`.
    MediusCatchClass class_;
    // The class-specific id, or `MEDIUS_CATCH_ID_ANY`.
    uint16_t id;
    // A `MEDIUS_DIRECTION_*` value: the press/release edge on the momentary classes, the sign of
    // the delta on axes, and IN (`Positive`) / OUT (`Negative`) on the traffic classes. A byte no
    // constant names is refused at subscribe time.
    // A byte rather than `MediusDirection`, so the boundary can validate it before anything reads it
    // as one; C++ renders the enum as `enum : uint8_t`, so assigning this to a `MediusDirection`
    // there needs a cast.
    uint8_t direction;
    // Bytes kept per event; 0 keeps the whole packet. Traffic classes only -- an input class carries
    // no packet, and naming one with a non-zero capture is refused at subscribe time.
    uint8_t capture;
} MediusCatchFilter;

// One row of a `MediusCatchState`: a live subscription and what it has lost.
typedef struct MediusCatchEntry {
    struct MediusCatchFilter filter;
    // Events this entry could not queue. Per entry, because a box-wide count says you are losing
    // events but not which ones, and those are different problems.
    uint16_t dropped;
} MediusCatchEntry;

// Decoded `RESP(CATCH)`: the live subscription table in `entries[0..n]`, its drop counts, and the
// measured inter-chip clock estimate.
typedef struct MediusCatchState {
    // The box refused an entry because its table is full.
    uint8_t table_full;
    // Box-wide events dropped under back-pressure.
    uint32_t dropped;
    struct MediusClockEstimate clock;
    // The number of valid entries in `entries`.
    uint16_t n;
    struct MediusCatchEntry entries[MEDIUS_MAX_CATCH_ENTRIES];
} MediusCatchState;

// Imperfect-clone opt-in and over-capacity status (each field is 0 or 1).
typedef struct MediusImperfectStatus {
    uint8_t allowed;
    uint8_t over_capacity;
    uint8_t clone_imperfect;
} MediusImperfectStatus;

// The configured bearing: what `MEDIUS_DIRECTION_WITH` / `_AGAINST` are measured against.
typedef struct MediusBearing {
    // How long the last injected delta's direction stays the bearing, in ms. 0 = never, which
    // leaves the relative directions inert whatever their scale.
    uint16_t window_ms;
    MediusBearingMode mode;
} MediusBearing;

// Emit-rate pacing mode plus the rate in effect and the rate the clone advertises.
typedef struct MediusEmitPaceStatus {
    MediusEmitMode mode;
    // 1 when the renderer composes onto `mode`, gating every 1 ms frame tick.
    uint8_t rendered;
    uint16_t fixed_hz;
    uint16_t resolved_hz;
    // The forced wire rate requested, in Hz; 0 leaves the device's own.
    uint16_t force_hz;
    // What the clone's input endpoints advertise now, in Hz; 0 = no clone.
    uint16_t advertised_hz;
    // 1 when a forced interval is written into the descriptor being served.
    uint8_t force_active;
} MediusEmitPaceStatus;

// Host-side always-on counters.
typedef struct MediusCountersSnapshot {
    uint64_t frames_tx;
    uint64_t frames_rx;
    uint64_t crc_drops;
    uint64_t reconnects;
} MediusCountersSnapshot;

// A keyboard key, addressed by HID Keyboard/Keypad usage. Modifiers are `0xE0..=0xE7`.
typedef uint8_t MediusKey;

// A media key, addressed by 16-bit HID Consumer usage.
typedef uint16_t MediusMediaKey;

// One held-usage snapshot: every held usage of one class in `usages[0..n]`.
typedef struct MediusUsageEvent {
    // Which class this snapshot is of, one of `MEDIUS_CLASS_*`. Carried here rather than read off
    // the first entry, because the snapshot that most needs it is the one with `n == 0`: releasing
    // the last held usage is the edge a caller waits for, and it lists nothing to read a class from.
    uint8_t class_;
    // A `MEDIUS_DIRECTION_*` value: the edge that produced this snapshot, the subscribed set having
    // grown (`Positive`) or shrunk (`Negative`). Without it a direction on an input filter cannot be
    // honoured at all.
    // A byte rather than `MediusDirection`, so the boundary can validate it before anything reads it
    // as one; C++ renders the enum as `enum : uint8_t`, so assigning this to a `MediusDirection`
    // there needs a cast.
    uint8_t direction;
    uint16_t n;
    struct MediusUsage usages[MEDIUS_MAX_USAGES];
} MediusUsageEvent;

// One byte-oriented catch event: HID reports, vendor endpoints, control transactions, the bytes the
// clone emitted, or bus lifecycle. `bytes[0..len]` is as much of the packet as `capture` kept.
typedef struct MediusTrafficEvent {
    // One of `MEDIUS_CATCH_CLASS_*`.
    MediusCatchClass class_;
    // Endpoint address, interface number, or endpoint number, per the class.
    uint16_t id;
    // A `MEDIUS_DIRECTION_*` value: `Positive` is IN (device to PC), `Negative` is OUT.
    // A byte rather than `MediusDirection`, so the boundary can validate it before anything reads it
    // as one; C++ renders the enum as `enum : uint8_t`, so assigning this to a `MediusDirection`
    // there needs a cast.
    uint8_t direction;
    // Class-specific; read it with `medius_traffic_event_control_status` or `..._bus_event`.
    uint8_t flags;
    // The packet's length before `capture` truncated it.
    uint16_t true_len;
    // Valid bytes in `bytes`.
    uint16_t len;
    uint8_t bytes[MEDIUS_MAX_TRAFFIC_BYTES];
} MediusTrafficEvent;

// A decoded bus lifecycle event; the payload fields are 0 for the kinds that carry none.
typedef struct MediusBusEvent {
    MediusBusEventKind kind;
    uint8_t configuration;
    uint8_t interface;
    uint8_t alt;
} MediusBusEvent;

// One relative-axis catch event: the user's real motion at the merge point, before lock suppression or injection.
typedef struct MediusMotionEvent {
    // Relative X this report (right positive).
    int16_t dx;
    // Relative Y this report (down positive).
    int16_t dy;
    // Wheel delta this report (up positive).
    int16_t dz;
} MediusMotionEvent;

// The populated arm of a [`MediusCatchEvent`]; read the field matching the event's `kind`.
typedef union MediusCatchEventData {
    struct MediusMotionEvent motion;
    struct MediusUsageEvent usages;
    struct MediusTrafficEvent traffic;
} MediusCatchEventData;

// One catch-stream event. Read `data.motion` / `data.usages` / `data.traffic` per `kind`.
typedef struct MediusCatchEvent {
    MediusCatchEventKind kind;
    // When the event was stamped, in the `clock` chip's microseconds. A box-local clock, unrelated
    // to any clock on this machine, so only meaningful compared against other events of the same
    // domain. It wraps every ~71.6 minutes and restarts at zero if that chip reboots, so a value
    // below the previous one is a wrap, a reboot, or a domain change, and the delta is meaningless.
    uint32_t ts_us;
    // Which chip's clock stamped `ts_us`.
    MediusClockDomain clock;
    union MediusCatchEventData data;
} MediusCatchEvent;

// One decoded input event: a press or release edge, or a motion report. The held-usage snapshots the
// box sends are diffed into these by `medius_device_input_events`.
typedef struct MediusInputEvent {
    MediusInputKind kind;
    // The report's arrival stamp, in the `clock` chip's microseconds.
    uint32_t ts_us;
    // Which chip's clock stamped it; always `HostChip` for physical input.
    MediusClockDomain clock;
    // The usage this is an edge on; unset for `Motion`.
    struct MediusUsage usage;
    // Relative X this report (right positive); 0 unless `kind` is `Motion`.
    int16_t dx;
    // Relative Y this report (down positive); 0 unless `kind` is `Motion`.
    int16_t dy;
    // Wheel delta this report (up positive); 0 unless `kind` is `Motion`.
    int16_t dz;
} MediusInputEvent;

// One event placed on this machine's clock by a `MediusTimeline`.
typedef struct MediusStamped {
    // When the event happened, on the same monotonic clock the caller passed as `now_ns`.
    uint64_t host_ns;
    // The event's own stamp, unwrapped past the 32-bit rollover.
    uint64_t box_us;
    // How much later than the measured floor this event reached the caller. Jitter, not latency.
    uint64_t excess_ns;
} MediusStamped;

// One device log line. `text` is NUL-terminated.
typedef struct MediusLogLine {
    MediusLogLevel level;
    char text[MEDIUS_MAX_LOG_TEXT];
} MediusLogLine;

#define MEDIUS_KEY_A 4

#define MEDIUS_KEY_B 5

#define MEDIUS_KEY_C 6

#define MEDIUS_KEY_D 7

#define MEDIUS_KEY_E 8

#define MEDIUS_KEY_F 9

#define MEDIUS_KEY_G 10

#define MEDIUS_KEY_H 11

#define MEDIUS_KEY_I 12

#define MEDIUS_KEY_J 13

#define MEDIUS_KEY_K 14

#define MEDIUS_KEY_L 15

#define MEDIUS_KEY_M 16

#define MEDIUS_KEY_N 17

#define MEDIUS_KEY_O 18

#define MEDIUS_KEY_P 19

#define MEDIUS_KEY_Q 20

#define MEDIUS_KEY_R 21

#define MEDIUS_KEY_S 22

#define MEDIUS_KEY_T 23

#define MEDIUS_KEY_U 24

#define MEDIUS_KEY_V 25

#define MEDIUS_KEY_W 26

#define MEDIUS_KEY_X 27

#define MEDIUS_KEY_Y 28

#define MEDIUS_KEY_Z 29

#define MEDIUS_KEY_1 30

#define MEDIUS_KEY_2 31

#define MEDIUS_KEY_3 32

#define MEDIUS_KEY_4 33

#define MEDIUS_KEY_5 34

#define MEDIUS_KEY_6 35

#define MEDIUS_KEY_7 36

#define MEDIUS_KEY_8 37

#define MEDIUS_KEY_9 38

#define MEDIUS_KEY_0 39

#define MEDIUS_KEY_ENTER 40

#define MEDIUS_KEY_ESCAPE 41

#define MEDIUS_KEY_BACKSPACE 42

#define MEDIUS_KEY_TAB 43

#define MEDIUS_KEY_SPACE 44

#define MEDIUS_KEY_CAPS_LOCK 57

#define MEDIUS_KEY_INSERT 73

#define MEDIUS_KEY_HOME 74

#define MEDIUS_KEY_PAGE_UP 75

#define MEDIUS_KEY_DELETE 76

#define MEDIUS_KEY_END 77

#define MEDIUS_KEY_PAGE_DOWN 78

#define MEDIUS_KEY_RIGHT 79

#define MEDIUS_KEY_LEFT 80

#define MEDIUS_KEY_DOWN 81

#define MEDIUS_KEY_UP 82

#define MEDIUS_KEY_F1 58

#define MEDIUS_KEY_F2 59

#define MEDIUS_KEY_F3 60

#define MEDIUS_KEY_F4 61

#define MEDIUS_KEY_F5 62

#define MEDIUS_KEY_F6 63

#define MEDIUS_KEY_F7 64

#define MEDIUS_KEY_F8 65

#define MEDIUS_KEY_F9 66

#define MEDIUS_KEY_F10 67

#define MEDIUS_KEY_F11 68

#define MEDIUS_KEY_F12 69

#define MEDIUS_KEY_LEFT_CTRL 224

#define MEDIUS_KEY_LEFT_SHIFT 225

#define MEDIUS_KEY_LEFT_ALT 226

#define MEDIUS_KEY_LEFT_GUI 227

#define MEDIUS_KEY_RIGHT_CTRL 228

#define MEDIUS_KEY_RIGHT_SHIFT 229

#define MEDIUS_KEY_RIGHT_ALT 230

#define MEDIUS_KEY_RIGHT_GUI 231

#define MEDIUS_MEDIA_PLAY_PAUSE 205

#define MEDIUS_MEDIA_STOP 183

#define MEDIUS_MEDIA_NEXT_TRACK 181

#define MEDIUS_MEDIA_PREV_TRACK 182

#define MEDIUS_MEDIA_MUTE 226

#define MEDIUS_MEDIA_VOLUME_UP 233

#define MEDIUS_MEDIA_VOLUME_DOWN 234

#define MEDIUS_MEDIA_PLAY 176

#define MEDIUS_MEDIA_PAUSE 177

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// A new empty clip-entry builder. The caller owns it and must free it with `medius_clip_builder_free`.
struct MediusClipBuilder *medius_clip_builder_new(void);

// Free a clip-entry builder. Null is a no-op.
void medius_clip_builder_free(struct MediusClipBuilder *b);

// Clear the builder to reuse it after an append.
MediusStatus medius_clip_builder_clear(struct MediusClipBuilder *b);

// A gap run: emit nothing for `frames` native frames (a zero count is a no-op).
MediusStatus medius_clip_builder_gap(struct MediusClipBuilder *b, uint16_t frames);

// A cursor-motion frame (`dx`/`dy`).
MediusStatus medius_clip_builder_move(struct MediusClipBuilder *b, int16_t dx, int16_t dy);

// A wheel frame.
MediusStatus medius_clip_builder_wheel(struct MediusClipBuilder *b, int16_t dz);

// A frame that presses a usage (a button, key, or media usage).
MediusStatus medius_clip_builder_press(struct MediusClipBuilder *b, struct MediusUsage usage);

// A frame that soft-releases a usage (clears the injected press; a physical hold is left intact).
MediusStatus medius_clip_builder_release(struct MediusClipBuilder *b, struct MediusUsage usage);

// A frame that force-releases a usage (masks a physical hold too).
MediusStatus medius_clip_builder_force_release(struct MediusClipBuilder *b,
                                               struct MediusUsage usage);

// A one-edge frame for any usage with an explicit `action`. `action` takes a `MEDIUS_ACTION_*`
// constant; any other value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_clip_builder_edge(struct MediusClipBuilder *b,
                                      struct MediusUsage usage,
                                      uint8_t action);

// A general content frame: a motion delta (`dx`/`dy`, `wheel`) plus `n` edges from parallel
// `inputs`/`actions` arrays. Each `actions` entry takes a `MEDIUS_ACTION_*` constant; any other
// value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_clip_builder_frame(struct MediusClipBuilder *b,
                                       int16_t dx,
                                       int16_t dy,
                                       int16_t wheel,
                                       const struct MediusUsage *inputs,
                                       const uint8_t *actions,
                                       uintptr_t n);

// A handle to this box's buffered-clip playback; free it with `medius_clip_free`.
MediusStatus medius_device_clip(struct MediusDevice *dev, struct MediusClip **out);

// Free a clip handle. Null is a no-op.
void medius_clip_free(struct MediusClip *clip);

// Append the builder's entries to the ring (whole-entry frames, each with the next append sequence).
MediusStatus medius_clip_append(struct MediusClip *clip,
                                const struct MediusClipBuilder *builder);

// Set the autolock scope: the input groups `scope` points at (NULL / 0 = none). Set before the first
// append. Each entry takes a `MEDIUS_BLANKET_*` constant; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_clip_set_autolock(struct MediusClip *clip,
                                      const uint8_t *scope,
                                      uintptr_t scope_len);

// Loop playback at the clip end (retained mode only).
MediusStatus medius_clip_set_loop(struct MediusClip *clip, uint8_t on);

// Retain the loaded clip so it can rewind and replay (0 = streaming, the default). Set before the first append.
MediusStatus medius_clip_set_retain(struct MediusClip *clip,
                                    uint8_t on);

// Make the clip's motion wait to ride a native report (0 = the box's own clock, the default).
MediusStatus medius_clip_set_ride(struct MediusClip *clip, uint8_t on);

// Add or overwrite a trigger binding. `trigger.edge` takes a `MEDIUS_EDGE_*` constant and
// `trigger.action` a `MEDIUS_CLIP_ACTION_*` one; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_clip_bind(struct MediusClip *clip, struct MediusClipTrigger trigger);

// Remove the trigger binding on `usage`'s `edge`. `edge` takes a `MEDIUS_EDGE_*` constant; any other
// value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_clip_unbind(struct MediusClip *clip,
                                struct MediusUsage usage,
                                uint8_t edge);

// Remove every trigger binding.
MediusStatus medius_clip_clear_triggers(struct MediusClip *clip);

// Rewind and play (resume from a pause).
MediusStatus medius_clip_start(struct MediusClip *clip);

// Stop, flush a streaming clip (rewind a retained one), release held input and the clip auto-lock.
MediusStatus medius_clip_stop(struct MediusClip *clip);

// Halt mid-clip, retaining the cursor and any held input.
MediusStatus medius_clip_pause(struct MediusClip *clip);

// Continue from the paused cursor.
MediusStatus medius_clip_resume(struct MediusClip *clip);

// Force a rewind and play, even mid-playback.
MediusStatus medius_clip_restart(struct MediusClip *clip);

// Toggle: play if idle/paused, stop if playing.
MediusStatus medius_clip_toggle(struct MediusClip *clip);

// Discard the loaded clip, free the ring, and clear a fault.
MediusStatus medius_clip_clear(struct MediusClip *clip);

// Finalize a retained clip: fix its end so it can replay and loop.
MediusStatus medius_clip_finalize(struct MediusClip *clip);

// Query the ring depth, progress, and playback counters. A `Faulted` state means recover with `medius_clip_clear`.
MediusStatus medius_clip_query_status(struct MediusClip *clip,
                                      struct MediusClipStatus *out);

// Query the clip configuration: autolock scope, loop/retain, finalized, and the trigger set.
MediusStatus medius_clip_query_config(struct MediusClip *clip, struct MediusClipSettings *out);

// Open the box at serial `path` (NUL-terminated UTF-8), handshake, and write the owned handle to `*out`.
MediusStatus medius_device_open(const char *path,
                                struct MediusDevice **out);

// Discover the first medius box by USB id, open it, handshake, and write the handle to `*out`.
MediusStatus medius_device_find(struct MediusDevice **out);

// Clone a device handle into another owner of the same reference-counted connection; each clone must be freed.
struct MediusDevice *medius_device_clone(const struct MediusDevice *dev);

// Free a device handle; joins the background threads when the last clone drops, null is a no-op.
void medius_device_free(struct MediusDevice *dev);

// Enumerate medius serial ports into `out` (up to `cap`); writes the total to `*out_total` and returns the number written.
uintptr_t medius_find_ports(struct MediusPortInfo *out,
                            uintptr_t cap,
                            uintptr_t *out_total);

// Enumerate every connected box into `out` (up to `cap`), opening each in turn; writes the total to `*out_total` and returns the number written.
uintptr_t medius_list(struct MediusBoxInfo *out,
                      uintptr_t cap,
                      uintptr_t *out_total);

// Open the box whose identity matches `id` (device MAC hex or CH343 serial), handshake, and write the handle to `*out`.
MediusStatus medius_device_open_by_id(const char *id,
                                      struct MediusDevice **out);

// Open the first box whose clone is a mouse, handshake, and write the handle to `*out`.
MediusStatus medius_device_find_mouse_box(struct MediusDevice **out);

// Open the first box whose clone is a keyboard, handshake, and write the handle to `*out`.
MediusStatus medius_device_find_keyboard_box(struct MediusDevice **out);

MediusStatus medius_device_move_rel(struct MediusDevice *dev, int16_t dx, int16_t dy);

MediusStatus medius_device_wheel(struct MediusDevice *dev, int16_t delta);

// A cursor move that bypasses movement riding: it emits on the box's own clock.
MediusStatus medius_device_move_rel_now(struct MediusDevice *dev, int16_t dx, int16_t dy);

// A wheel move that bypasses movement riding.
MediusStatus medius_device_wheel_now(struct MediusDevice *dev, int16_t delta);

// Emit the motion held for a ride now, ignoring the ride window.
MediusStatus medius_device_flush_motion(struct MediusDevice *dev);

// Drop the motion held for a ride.
MediusStatus medius_device_discard_motion(struct MediusDevice *dev);

// Drive one relative axis. `motion.kind` takes a `MEDIUS_MOTION_KIND_*` constant, `timing` a
// `MEDIUS_MOVE_TIMING_*` one and `pending` a `MEDIUS_PENDING_MOTION_*` one; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_move_axis(struct MediusDevice *dev,
                                     struct MediusMotion motion,
                                     uint8_t timing,
                                     uint8_t pending);

// Drive one momentary usage (button, key, or media) with an explicit action. The one injection verb.
// `action` takes a `MEDIUS_ACTION_*` constant; any other value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_inject(struct MediusDevice *dev,
                                  struct MediusUsage input,
                                  uint8_t action);

// Press a usage (`Action::Press`).
MediusStatus medius_device_press(struct MediusDevice *dev, struct MediusUsage input);

// Soft-release a usage: clear an injected press, leaving a physical hold intact.
MediusStatus medius_device_soft_release(struct MediusDevice *dev, struct MediusUsage input);

// Force-release a usage: mask a physical hold too.
MediusStatus medius_device_force_release(struct MediusDevice *dev, struct MediusUsage input);

// Weigh physical input on a target and direction. `scale` is the percent of the physical value the
// box keeps: `MEDIUS_LOCK_SCALE_BLOCK` blocks it, `MEDIUS_LOCK_SCALE_PASS` passes it untouched, and
// above that amplifies to `MEDIUS_LOCK_SCALE_MAX` (2.55x). Lock and unlock are its two ends.
//
// A delta picks up at most two scales, its absolute direction's and its relative direction's, and
// they multiply. `MEDIUS_DIRECTION_BOTH` is the exception: it writes the scale to the two fixed
// signs and a full pass to the relative pair, so a `Both` of 50 is 50% with or without a bearing
// rather than 25% with one. Name a relative direction to weigh it.
//
// `MEDIUS_DIRECTION_WITH` / `_AGAINST` need a live bearing (see `medius_device_set_bearing`) and
// only an axis has one, so either on a button, key or media usage is
// `MEDIUS_STATUS_ERR_RELATIVE_DIRECTION`. A momentary usage carries one bit, so any scale below a full
// pass locks it and any scale at or above one unlocks it. A media usage has no edges and is sent as
// `MEDIUS_DIRECTION_BOTH` whatever edge is named, which is what `RESP(LOCKS)` reports it as.
//
// `dir` takes a `MEDIUS_DIRECTION_*` constant; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_scale(struct MediusDevice *dev,
                                 struct MediusLockTarget target,
                                 uint8_t dir,
                                 uint8_t scale);

// Weigh a whole class blanket (cursor aim, wheel, all buttons, all keys, or all media). `what` takes
// a `MEDIUS_BLANKET_*` constant and `dir` a `MEDIUS_DIRECTION_*` one; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_scale_all(struct MediusDevice *dev,
                                     uint8_t what,
                                     uint8_t dir,
                                     uint8_t scale);

// Lock a target (axis or usage) on an edge. A button, key, and media usage all lock the same way.
// `dir` takes a `MEDIUS_DIRECTION_*` constant; any other value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_lock(struct MediusDevice *dev,
                                struct MediusLockTarget target,
                                uint8_t dir);

// Release a lock set by `medius_device_lock`. `dir` takes a `MEDIUS_DIRECTION_*` constant; any other
// value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_unlock(struct MediusDevice *dev,
                                  struct MediusLockTarget target,
                                  uint8_t dir);

// Lock a whole class blanket (cursor aim, wheel, all buttons, all keys, or all media).
//
// `MEDIUS_BLANKET_KEYS` honours the direction: `Positive` blocks press edges only, `Negative`
// release edges only. `what` takes a `MEDIUS_BLANKET_*` constant and `dir` a `MEDIUS_DIRECTION_*`
// one; any other value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_lock_all(struct MediusDevice *dev, uint8_t what, uint8_t dir);

// Release a blanket lock set by `medius_device_lock_all`. `what` takes a `MEDIUS_BLANKET_*` constant
// and `dir` a `MEDIUS_DIRECTION_*` one; any other value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_unlock_all(struct MediusDevice *dev,
                                      uint8_t what,
                                      uint8_t dir);

// Drive a status LED. `target` takes a `MEDIUS_LED_TARGET_*` constant and `mode` a
// `MEDIUS_LED_MODE_*` one; any other value is `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_led(struct MediusDevice *dev,
                               uint8_t target,
                               uint8_t mode,
                               uint8_t level);

MediusStatus medius_device_reset(struct MediusDevice *dev);

MediusStatus medius_device_reapply(struct MediusDevice *dev);

MediusStatus medius_device_reconnect(struct MediusDevice *dev);

// Reboot a chip. `target` takes a `MEDIUS_REBOOT_TARGET_*` constant; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_reboot(struct MediusDevice *dev, uint8_t target);

MediusStatus medius_device_allow_imperfect_clones(struct MediusDevice *dev, bool allow);

// Set movement riding; when `enabled`, injected motion rides a native cursor report seen within `window_ms`.
MediusStatus medius_device_set_movement_riding(struct MediusDevice *dev,
                                               bool enabled,
                                               uint32_t window_ms);

// Set the bearing: what `MEDIUS_DIRECTION_WITH` / `_AGAINST` are measured against. `window_ms` is how
// long the last injected delta's direction stays the bearing; 0 turns it off, leaving the relative
// directions inert whatever their scale. The box boots at `MEDIUS_BEARING_WINDOW_DEFAULT_MS`.
//
// `mode` takes a `MEDIUS_BEARING_MODE_*` constant; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`. Both fields ride one frame and the box persists them together,
// so a window change carries the mode with it.
MediusStatus medius_device_set_bearing(struct MediusDevice *dev,
                                       uint16_t window_ms,
                                       uint8_t mode);

// Set what paces injected motion and what rate the clone runs at; `hz` is the target rate for `Fixed`
// and ignored otherwise, `rendered` composes the renderer onto the mode, `force_hz` is the forced wire
// rate (0 = the device's own). `mode` takes a `MEDIUS_EMIT_MODE_*` constant; any other value is
// `MEDIUS_STATUS_ERR_INVALID_ARG`.
MediusStatus medius_device_set_emit_pace(struct MediusDevice *dev,
                                         uint8_t mode,
                                         uint16_t hz,
                                         bool rendered,
                                         uint16_t force_hz);

// Set the box's persistent name (`name`, NUL-terminated UTF-8); an empty string clears it.
MediusStatus medius_device_set_name(struct MediusDevice *dev, const char *name);

// Clear the box's custom name, reverting it to its synthesized `Medius-XXXX` default.
MediusStatus medius_device_clear_name(struct MediusDevice *dev);

MediusStatus medius_device_query_version(struct MediusDevice *dev, struct MediusVersion *out);

// Both chips' firmware versions and slot state.
MediusStatus medius_device_firmware_info(struct MediusDevice *dev, struct MediusFirmwareInfo *out);

// Write `len` bytes into `target`'s spare slot (0 = device chip, 1 = host chip). The image stays
// inert until medius_device_activate_firmware. `progress`, if non-null, is called with bytes sent
// and the total.
MediusStatus medius_device_stage_firmware(struct MediusDevice *dev,
                                          uint8_t target,
                                          const uint8_t *image,
                                          uintptr_t len,
                                          void (*progress)(void*, uintptr_t, uintptr_t),
                                          void *user);

// Drop whatever is staged or in flight for one target; the clone comes back without a reboot.
MediusStatus medius_device_abort_update(struct MediusDevice *dev, uint8_t target);

// Commit every staged image and reboot into it. Blocks while the host chip reboots and comes back.
MediusStatus medius_device_activate_firmware(struct MediusDevice *dev);

MediusStatus medius_device_query_health(struct MediusDevice *dev, struct MediusHealth *out);

MediusStatus medius_device_device_info(struct MediusDevice *dev, struct MediusDeviceInfo *out);

MediusStatus medius_device_caps(struct MediusDevice *dev, struct MediusCaps *out);

MediusStatus medius_device_query_rate(struct MediusDevice *dev, struct MediusRate *out);

MediusStatus medius_device_query_stats(struct MediusDevice *dev, struct MediusStats *out);

MediusStatus medius_device_query_locks(struct MediusDevice *dev, struct MediusLocks *out);

MediusStatus medius_device_query_catch(struct MediusDevice *dev, struct MediusCatchState *out);

MediusStatus medius_device_query_imperfect(struct MediusDevice *dev,
                                           struct MediusImperfectStatus *out);

// Query the bearing into `*out`.
MediusStatus medius_device_query_bearing(struct MediusDevice *dev, struct MediusBearing *out);

// Query the movement-riding window into `*out_enabled` and `*out_window_ms` (0 when off).
MediusStatus medius_device_query_movement_riding(struct MediusDevice *dev,
                                                 bool *out_enabled,
                                                 uint32_t *out_window_ms);

MediusStatus medius_device_query_emit_pace(struct MediusDevice *dev,
                                           struct MediusEmitPaceStatus *out);

MediusStatus medius_device_counters(struct MediusDevice *dev, struct MediusCountersSnapshot *out);

// Default RESP wait before a query times out, in milliseconds.
uint32_t medius_default_query_timeout_ms(void);

// Default keepalive cadence for held overrides, in milliseconds.
uint32_t medius_default_keepalive_cadence_ms(void);

// The C ABI version, bumped on any breaking change to this header.
uint32_t medius_abi_version(void);

// The medius-capi crate version as a static NUL-terminated string.
const char *medius_version_string(void);

// Copy the last error text into `buf` (NUL-terminated, truncated to `cap`); returns the full byte length excluding the NUL.
uintptr_t medius_last_error_message(char *buf,
                                    uintptr_t cap);

// The `BadProtoVer` version byte from the last error, or 0 if the last error carried none.
uint8_t medius_last_error_proto_ver(void);

// Build an [`MediusUsage`] addressing a mouse button. `button` takes a `MEDIUS_BUTTON_*` constant;
// a byte no constant names is carried through and refused by the call that takes the usage, since a
// constructor has no status to return.
struct MediusUsage medius_usage_button(uint8_t button);

// Build an [`MediusUsage`] addressing a keyboard key.
struct MediusUsage medius_usage_key(MediusKey key);

// Build an [`MediusUsage`] addressing a media key.
struct MediusUsage medius_usage_media(MediusMediaKey media);

// Build a cursor-motion [`MediusMotion`].
struct MediusMotion medius_motion_cursor(int16_t dx, int16_t dy);

// Build a wheel [`MediusMotion`].
struct MediusMotion medius_motion_wheel(int16_t delta);

// Build a [`MediusLockTarget`] addressing an axis: `kind` takes `MEDIUS_LOCK_TARGET_KIND_X`, `_Y` or
// `_WHEEL`. Any other byte is carried through and refused by the call that takes the target, since a
// constructor has no status to return.
struct MediusLockTarget medius_lock_target_axis(uint8_t kind);

// Build a [`MediusLockTarget`] addressing a momentary usage (button, key, or media).
struct MediusLockTarget medius_lock_target_usage(struct MediusUsage usage);

// The scale in effect on `target`/`dir`: percent of the physical value kept, so
// `MEDIUS_LOCK_SCALE_PASS` when nothing weighs it. `Both` reports the lowest across every direction.
// Mirrors `medius::Locks::scale_of`. `dir` takes a `MEDIUS_DIRECTION_*` constant; any other value
// names no entry and reads as `MEDIUS_LOCK_SCALE_PASS`.
uint8_t medius_locks_scale_of(const struct MediusLocks *locks,
                              struct MediusLockTarget target,
                              uint8_t dir);

// Whether `target`/`dir` is blocked outright in `locks`. A direction merely weighed is not locked.
// `Both` asks about the two fixed signs, the pair it has always named; ask for a relative direction
// by name. Mirrors `medius::Locks::is_locked`. `dir` takes a `MEDIUS_DIRECTION_*` constant; any
// other value names no entry and reads as unlocked.
bool medius_locks_is_locked(const struct MediusLocks *locks,
                            struct MediusLockTarget target,
                            uint8_t dir);

// The native report rate in Hz written to `out_hz`, false when there is no continuous cadence. Delegates to `medius::Rate::native_hz`.
bool medius_rate_native_hz(struct MediusRate rate,
                           float *out_hz);

// Whether `usage` is held in a usage snapshot. Mirrors `medius::UsageSnapshot::is_held`.
bool medius_usage_event_is_held(const struct MediusUsageEvent *event, struct MediusUsage usage);

// One momentary usage: a button, a key, or a media usage. The same thing `medius_device_lock` takes.
// A `usage.kind` no `MEDIUS_CLASS_*` constant names yields a filter subscribing refuses.
struct MediusCatchFilter medius_catch_filter_watch(struct MediusUsage usage);

// One relative axis. `axis` takes a `MEDIUS_AXIS_*` constant; any other byte yields a filter
// subscribing refuses.
struct MediusCatchFilter medius_catch_filter_watch_axis(uint8_t axis);

// Every usage in one momentary class. `class` takes a `MEDIUS_CLASS_*` constant; any other byte
// yields a filter subscribing refuses.
struct MediusCatchFilter medius_catch_filter_watch_class(uint8_t class_);

// Every relative axis: X, Y and the wheel.
struct MediusCatchFilter medius_catch_filter_watch_axes(void);

// Write the four input-class filters to `out[0..4]`: buttons, keys, media and axes. This is the
// whole of what `medius_device_input_events` can report.
//
// # Safety
// `out` must point to space for four `MediusCatchFilter`.
void medius_catch_filter_all_input(struct MediusCatchFilter *out);

// One traffic address: an endpoint, an interface, or a control endpoint number. `class` must be one
// of the traffic classes (`MEDIUS_CATCH_CLASS_HID_IN` upwards).
struct MediusCatchFilter medius_catch_filter_traffic(MediusCatchClass class_, uint16_t id);

// Every id within one traffic class.
struct MediusCatchFilter medius_catch_filter_traffic_class(MediusCatchClass class_);

// Every class, every id, both directions, whole packets. One table entry, not an expansion.
//
// This includes `MEDIUS_CATCH_CLASS_VENDOR_BULK`, which can saturate the control link by itself.
// Pair it with `medius_catch_filter_with_capture` unless you mean to trace bulk in full.
struct MediusCatchFilter medius_catch_filter_everything(void);

// `f` restricted to one direction, sign or edge. `direction` takes a `MEDIUS_DIRECTION_*` constant;
// a byte no constant names is carried through and refused at subscribe time with
// `MEDIUS_STATUS_ERR_INVALID_ARG`, since a filter has no status to return here.
struct MediusCatchFilter medius_catch_filter_with_direction(struct MediusCatchFilter f,
                                                            uint8_t direction);

// `f` keeping only the first `bytes` of each packet; 0 keeps the whole packet. Traffic classes only.
struct MediusCatchFilter medius_catch_filter_with_capture(struct MediusCatchFilter f,
                                                          uint8_t bytes);

// `f` restricted to the press edge.
struct MediusCatchFilter medius_catch_filter_on_press(struct MediusCatchFilter f);

// `f` restricted to the release edge.
struct MediusCatchFilter medius_catch_filter_on_release(struct MediusCatchFilter f);

// `f` restricted to traffic from the device to the PC.
struct MediusCatchFilter medius_catch_filter_inbound(struct MediusCatchFilter f);

// `f` restricted to traffic from the PC to the device.
struct MediusCatchFilter medius_catch_filter_outbound(struct MediusCatchFilter f);

// Whether two filters name the same box table entry, whatever their captures.
bool medius_catch_filter_same_address(struct MediusCatchFilter a, struct MediusCatchFilter b);

// Whether `class` is one of the four parsed-input classes, which arrive decoded and carry no packet.
bool medius_catch_class_is_input(MediusCatchClass class_);

// Whether `class` is one of the seven byte-oriented traffic classes.
bool medius_catch_class_is_traffic(MediusCatchClass class_);

// Whether the capture cut this packet short. Without checking, a truncated capture and a genuinely
// short packet are indistinguishable. Mirrors `medius::TrafficEvent::truncated`.
bool medius_traffic_event_truncated(const struct MediusTrafficEvent *event);

// The 8-byte setup packet of a CONTROL event, or NULL for another class or a capture cut shorter
// than the setup stage. Points into `event`. Mirrors `medius::TrafficEvent::setup`.
const uint8_t *medius_traffic_event_setup(const struct MediusTrafficEvent *event);

// The data stage of a CONTROL event, the whole packet for any other class; its length goes to
// `*out_len`. Points into `event`. Mirrors `medius::TrafficEvent::data`.
const uint8_t *medius_traffic_event_data(const struct MediusTrafficEvent *event,
                                         uintptr_t *out_len);

// What the real device answered, written to `*out`; false for any class but CONTROL. Mirrors
// `medius::TrafficEvent::control_status`.
bool medius_traffic_event_control_status(const struct MediusTrafficEvent *event,
                                         MediusControlStatus *out);

// The lifecycle event, written to `*out`; false for any class but BUS or an unknown kind. Mirrors
// `medius::TrafficEvent::bus_event`.
bool medius_traffic_event_bus_event(const struct MediusTrafficEvent *event,
                                    struct MediusBusEvent *out);

// Whether this event carries end-of-transfer, for a VEND_BULK event. Mirrors
// `medius::TrafficEvent::bulk_end_of_transfer`.
bool medius_traffic_event_bulk_end_of_transfer(const struct MediusTrafficEvent *event);

// Whether this event is a zero-length packet, for a VEND_BULK event. A ZLP terminates a transfer
// whose length is an exact multiple of the packet size, so it carries no bytes and still matters.
// Mirrors `medius::TrafficEvent::bulk_zlp`.
bool medius_traffic_event_bulk_zlp(const struct MediusTrafficEvent *event);

// Whether the clip is currently holding `usage` down. Mirrors `medius::ClipStatus::is_held`.
bool medius_clip_status_is_held(const struct MediusClipStatus *status, struct MediusUsage usage);

// Whether a mouse interface is bound. Delegates to `medius::Caps::has_mouse`.
bool medius_caps_has_mouse(struct MediusCaps caps);

// Whether a keyboard interface is bound. Delegates to `medius::Caps::has_keyboard`.
bool medius_caps_has_keyboard(struct MediusCaps caps);

// Whether the clone is composite (multi-HID-interface). Delegates to `medius::Caps::is_composite`.
bool medius_caps_is_composite(struct MediusCaps caps);

// Subscribe to the catch stream for `filters[0..n]` (build them with the `medius_catch_filter_*` helpers); writes the handle to `*out`.
MediusStatus medius_device_catch_events(struct MediusDevice *dev,
                                        const struct MediusCatchFilter *filters,
                                        uintptr_t n,
                                        struct MediusEventStream **out);

// Clone an event-stream handle onto the same subscription (shared queue); null in returns null out.
struct MediusEventStream *medius_event_stream_clone(const struct MediusEventStream *stream);

// Free an event-stream handle. Null is a no-op.
void medius_event_stream_free(struct MediusEventStream *stream);

// Block until the next physical-input event, writing it to `*out`; `ErrDisconnected` on close.
MediusStatus medius_event_stream_recv(struct MediusEventStream *stream,
                                      struct MediusCatchEvent *out);

// The next buffered event, written to `*out`; returns false if none is queued (never blocks).
bool medius_event_stream_try_recv(struct MediusEventStream *stream, struct MediusCatchEvent *out);

// Block up to `timeout_ms` for the next event, written to `*out`; returns false on timeout or close.
bool medius_event_stream_recv_timeout(struct MediusEventStream *stream,
                                      uint64_t timeout_ms,
                                      struct MediusCatchEvent *out);

// Events this stream dropped because the consumer fell behind (host-side back-pressure).
uint64_t medius_event_stream_dropped(struct MediusEventStream *stream);

// Subscribe to decoded input edges for `filters[0..n]`, writing the handle to `*out`.
//
// Every filter must name an input class and cover both edges; build them with
// `medius_catch_filter_watch*` or `medius_catch_filter_all_input`. A traffic class, the everything
// filter, or a filter narrowed to one edge is refused rather than silently yielding nothing.
//
// # Safety
// `filters` must point to `n` readable `MediusCatchFilter`; `dev` and `out` must be non-null.
MediusStatus medius_device_input_events(struct MediusDevice *dev,
                                        const struct MediusCatchFilter *filters,
                                        uintptr_t n,
                                        struct MediusInputStream **out);

// Free an input-stream handle. Null is a no-op.
//
// # Safety
// `stream` must come from `medius_device_input_events` and not be used afterwards.
void medius_input_stream_free(struct MediusInputStream *stream);

// Block until the next input event, writing it to `*out`; `ErrDisconnected` on close.
//
// # Safety
// `stream` and `out` must be non-null and valid.
MediusStatus medius_input_stream_recv(struct MediusInputStream *stream,
                                      struct MediusInputEvent *out);

// The next decoded event, written to `*out`; returns false if none is queued (never blocks).
//
// # Safety
// `stream` and `out` must be non-null and valid.
bool medius_input_stream_try_recv(struct MediusInputStream *stream, struct MediusInputEvent *out);

// Block up to `timeout_ms` for the next input event; returns false on timeout or close.
//
// # Safety
// `stream` and `out` must be non-null and valid.
bool medius_input_stream_recv_timeout(struct MediusInputStream *stream,
                                      uint64_t timeout_ms,
                                      struct MediusInputEvent *out);

// Events the underlying subscription dropped because the consumer fell behind.
//
// # Safety
// `stream` must be non-null and valid, or null.
uint64_t medius_input_stream_dropped(struct MediusInputStream *stream);

// Write the usages of `class` this stream currently holds to `out[0..cap]` and return how many there
// are. A return above `cap` means the buffer was too small and only `cap` were written. `class`
// takes a `MEDIUS_CLASS_*` constant; any other value holds nothing and reads as 0.
//
// # Safety
// `out` must point to space for `cap` `MediusUsage`.
uintptr_t medius_input_stream_held(struct MediusInputStream *stream,
                                   uint8_t class_,
                                   struct MediusUsage *out,
                                   uintptr_t cap);

// A fresh timeline. Free with `medius_timeline_free`.
struct MediusTimeline *medius_timeline_new(void);

// Free a timeline. Null is a no-op.
//
// # Safety
// `t` must come from `medius_timeline_new` and not be used afterwards.
void medius_timeline_free(struct MediusTimeline *t);

// Place `ev` on the caller's clock, writing the result to `*out`; returns false on a null argument.
//
// `now_ns` is the caller's own monotonic reading at the moment the event arrived, in nanoseconds
// from any fixed origin. `MediusStamped::host_ns` comes back on that same scale.
//
// # Safety
// `t`, `ev` and `out` must be non-null and valid.
bool medius_timeline_observe(struct MediusTimeline *t,
                             const struct MediusCatchEvent *ev,
                             uint64_t now_ns,
                             struct MediusStamped *out);

// Place a decoded input event on the caller's clock; the input-stream counterpart of
// `medius_timeline_observe`. Both share one timeline, so a caller reading both streams gets one
// comparable ordering.
//
// # Safety
// `t`, `ev` and `out` must be non-null and valid.
bool medius_timeline_observe_input(struct MediusTimeline *t,
                                   const struct MediusInputEvent *ev,
                                   uint64_t now_ns,
                                   struct MediusStamped *out);

// Forget one domain's rollover count and measured floor, for a chip that rebooted. `domain` takes a
// `MEDIUS_CLOCK_DOMAIN_*` constant; any other value is a no-op.
//
// # Safety
// `t` must be non-null and valid, or null.
void medius_timeline_reset(struct MediusTimeline *t, uint8_t domain);

// Events observed for a domain. The floor is a minimum over these: a handful is a loose estimate.
// `domain` takes a `MEDIUS_CLOCK_DOMAIN_*` constant; any other value reads as 0.
//
// # Safety
// `t` must be non-null and valid, or null.
uint64_t medius_timeline_samples(struct MediusTimeline *t, uint8_t domain);

// Whether the box is still delivering to this stream.
//
// `medius_event_stream_recv_timeout` and `_try_recv` both return `false` for "nothing yet" and for
// "nothing ever again". This separates them: one means wait longer, the other means stop.
//
// # Safety
// `stream` must be non-null and valid, or null.
bool medius_event_stream_is_connected(struct MediusEventStream *stream);

// Whether the box is still delivering to this input stream. See
// `medius_event_stream_is_connected`.
//
// # Safety
// `stream` must be non-null and valid, or null.
bool medius_input_stream_is_connected(struct MediusInputStream *stream);

// Open the device LOG stream, writing the handle to `*out`.
MediusStatus medius_device_logs(struct MediusDevice *dev, struct MediusLogStream **out);

// Clone a log-stream handle: another handle to the same LOG channel. Null in -> null out.
struct MediusLogStream *medius_log_stream_clone(const struct MediusLogStream *stream);

// Free a log-stream handle. Null is a no-op.
void medius_log_stream_free(struct MediusLogStream *stream);

// Block until the next LOG line, writing it to `*out`. Returns `ErrDisconnected` on close.
MediusStatus medius_log_stream_recv(struct MediusLogStream *stream, struct MediusLogLine *out);

// The next buffered LOG line, written to `*out`; returns false if none is queued (never blocks).
bool medius_log_stream_try_recv(struct MediusLogStream *stream, struct MediusLogLine *out);

// Block up to `timeout_ms` for the next LOG line, written to `*out`; false on timeout or close.
bool medius_log_stream_recv_timeout(struct MediusLogStream *stream,
                                    uint64_t timeout_ms,
                                    struct MediusLogLine *out);

#if defined(MEDIUS_FEATURE_MOCK)
// Create a fresh mock that records commands and auto-answers queries with defaults.
struct MediusMockBox *medius_mock_new(void);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Clone a mock handle: another handle sharing the same recorded state (like `MockBox::clone`).
struct MediusMockBox *medius_mock_clone(const struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Free a mock handle. Null is a no-op.
void medius_mock_free(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the version the mock answers to a VERSION query.
void medius_mock_set_version(struct MediusMockBox *mock, struct MediusVersion value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the health flags the mock answers to a HEALTH query.
void medius_mock_set_health(struct MediusMockBox *mock, struct MediusHealth value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the device identity the mock answers to a DEVICE_INFO query. `value.kind` takes a
// `MEDIUS_DEVICE_KIND_*` constant; any other value is ignored, as these setters have no status.
void medius_mock_set_device_info(struct MediusMockBox *mock, struct MediusDeviceInfo value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the whole capabilities (mouse + keyboard) the mock answers to a CAPS query.
void medius_mock_set_caps(struct MediusMockBox *mock, struct MediusCaps value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set only the mouse half of the capabilities.
void medius_mock_set_mouse_caps(struct MediusMockBox *mock, struct MediusMouseCaps value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set only the keyboard half of the capabilities (and mark the keyboard class change-driven).
void medius_mock_set_kbd_caps(struct MediusMockBox *mock, struct MediusKbdCaps value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the rate the mock answers to a RATE query.
void medius_mock_set_rate(struct MediusMockBox *mock, struct MediusRate value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the stats the mock answers to a STATS query.
void medius_mock_set_stats(struct MediusMockBox *mock, struct MediusStats value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the lock bitmask the mock answers to a LOCKS query.
void medius_mock_set_locks(struct MediusMockBox *mock, struct MediusLocks value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the catch state the mock answers to a CATCH query.
void medius_mock_set_catch_state(struct MediusMockBox *mock, struct MediusCatchState value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the imperfect-clone status the mock answers to an OPTION(IMPERFECT) query.
void medius_mock_set_imperfect_status(struct MediusMockBox *mock,
                                      struct MediusImperfectStatus value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the movement-riding window the mock answers to a query; `enabled == false` means off.
void medius_mock_set_movement_riding(struct MediusMockBox *mock, bool enabled, uint32_t window_ms);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the bearing the mock answers to an OPTION(BEARING) query; `window_ms` 0 = off. `mode` takes a
// `MEDIUS_BEARING_MODE_*` constant; any other value is ignored, as the box ignores it.
void medius_mock_set_bearing(struct MediusMockBox *mock, uint16_t window_ms, uint8_t mode);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the emit-rate pacing mode and the forced wire rate the mock answers to an OPTION(EMIT) query;
// `hz` matters only for `Fixed`, `force_hz` 0 means unforced. `mode` takes a `MEDIUS_EMIT_MODE_*`
// constant; any other value leaves the pacing mode alone.
void medius_mock_set_emit_pace(struct MediusMockBox *mock,
                               uint8_t mode,
                               uint16_t hz,
                               uint16_t force_hz);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the rate the mock's clone advertises unforced, in Hz; 0 means no clone.
void medius_mock_set_advertised_hz(struct MediusMockBox *mock, uint16_t hz);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the [`ClipStatus`](medius::ClipStatus) the mock answers to `medius_clip_query_status`.
// `value.state` takes a `MEDIUS_CLIP_STATE_*` constant; any other value is ignored.
void medius_mock_set_clip_status(struct MediusMockBox *mock, struct MediusClipStatus value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the [`ClipSettings`](medius::ClipSettings) the mock answers to `medius_clip_query_config`.
void medius_mock_set_clip_settings(struct MediusMockBox *mock, struct MediusClipSettings value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Make the mock unresponsive to queries (it still records commands). One-way, for testing timeouts.
void medius_mock_silent(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Inject raw bytes into the host's inbound stream, as if the box put them on the wire.
void medius_mock_push_raw(struct MediusMockBox *mock, const uint8_t *bytes, uintptr_t len);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a LOG line as if the box emitted it (surfaces on the device's log stream). `level` takes a
// `MEDIUS_LOG_LEVEL_*` constant; any other value reads as `INFO`, which is what the wire decoder
// does with a level byte it does not know.
void medius_mock_push_log(struct MediusMockBox *mock, uint8_t level, const char *text);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a MOTION_EVENT as if the box emitted it (surfaces as a `Motion` catch event).
void medius_mock_push_motion(struct MediusMockBox *mock,
                             uint8_t seq,
                             uint32_t ts_us,
                             struct MediusMotionEvent event);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a USAGE_EVENT as if the box emitted it (surfaces as a `Usages` catch event).
void medius_mock_push_usages(struct MediusMockBox *mock,
                             uint8_t seq,
                             uint32_t ts_us,
                             const struct MediusUsageEvent *event);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a TRAFFIC_EVENT as if the box emitted it (surfaces as a `Traffic` catch event).
// `true_len` above `len` is how a snaplen-truncated capture looks.
void medius_mock_push_traffic(struct MediusMockBox *mock,
                              uint8_t seq,
                              uint32_t ts_us,
                              uint8_t clock,
                              const struct MediusTrafficEvent *event);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// The number of commands the host has sent to the mock so far.
uintptr_t medius_mock_recorded(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Whether the host has sent at least one frame of the given type. `ty` takes a
// `MEDIUS_FRAME_TYPE_*` constant; any other value reads as false.
bool medius_mock_saw(struct MediusMockBox *mock, uint8_t ty);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Clear the recorded-command log.
void medius_mock_clear_recorded(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Read recorded frame `idx`: type to `*out_ty`, SEQ to `*out_seq`, up to `cap` payload bytes to `payload_buf`; returns the full payload length, or 0 if `idx` is out of range.
uintptr_t medius_mock_recorded_frame(struct MediusMockBox *mock,
                                     uintptr_t idx,
                                     MediusFrameType *out_ty,
                                     uint8_t *out_seq,
                                     uint8_t *payload_buf,
                                     uintptr_t cap);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Build a `Device` over the mock WITHOUT a handshake (clones the mock's shared state).
MediusStatus medius_device_with_mock(const struct MediusMockBox *mock, struct MediusDevice **out);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Build a `Device` over the mock AND run the version handshake (can fail if the mock is silent).
MediusStatus medius_device_open_mock(const struct MediusMockBox *mock, struct MediusDevice **out);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MEDIUS_H */
