/* medius C ABI. See https://github.com/K4HVH/medius. MIT. */

#ifndef MEDIUS_H
#define MEDIUS_H

#pragma once

/* Generated by tools/gen-header.sh (cbindgen). Do not edit by hand. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Largest number of pressed keys / active media usages in one catch snapshot. The wire format
// length-prefixes both lists with a `u8`, so 256 can never truncate.
#define MEDIUS_MAX_KEYS 256

// See [`MEDIUS_MAX_KEYS`].
#define MEDIUS_MAX_MEDIA_KEYS 256

// Capacity for a log line's text (the wire payload is at most 512 bytes).
#define MEDIUS_MAX_LOG_TEXT 512

// Capacity for a discovered serial-port path.
#define MEDIUS_MAX_PATH 512

// CATCH subscription class bits, OR them together (see `medius_device_catch_events`).
#define MEDIUS_CATCH_MASK_MOTION 1

#define MEDIUS_CATCH_MASK_WHEEL 2

#define MEDIUS_CATCH_MASK_BUTTONS 4

#define MEDIUS_CATCH_MASK_KEYS 8

#define MEDIUS_CATCH_MASK_ALL 15

// The result of a fallible `medius_*` call. `MEDIUS_OK` is zero; everything else is a failure.
enum MediusStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_STATUS_OK = 0,
    MEDIUS_STATUS_ERR_IO = 1,
    MEDIUS_STATUS_ERR_NOT_FOUND = 2,
    MEDIUS_STATUS_ERR_NO_REPLY = 3,
    MEDIUS_STATUS_ERR_BAD_PROTO_VER = 4,
    MEDIUS_STATUS_ERR_QUERY_TIMEOUT = 5,
    MEDIUS_STATUS_ERR_DISCONNECTED = 6,
    MEDIUS_STATUS_ERR_FRAME_TOO_LONG = 7,
    MEDIUS_STATUS_ERR_FLASH_TOOL = 8,
    MEDIUS_STATUS_ERR_INVALID_ARG = 9,
    MEDIUS_STATUS_ERR_PANIC = 10,
    MEDIUS_STATUS_ERR_UNKNOWN = 11,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusStatus MediusStatus;
#else
typedef int32_t MediusStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which arm of a [`MediusMotion`] is populated.
enum MediusMotionKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_MOTION_KIND_CURSOR = 0,
    MEDIUS_MOTION_KIND_WHEEL = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusMotionKind MediusMotionKind;
#else
typedef uint8_t MediusMotionKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which arm of a [`MediusInput`] is populated.
enum MediusInputKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_INPUT_KIND_BUTTON = 0,
    MEDIUS_INPUT_KIND_KEY = 1,
    MEDIUS_INPUT_KIND_MEDIA = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusInputKind MediusInputKind;
#else
typedef uint8_t MediusInputKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// An injection override action.
enum MediusAction
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_ACTION_SOFT_RELEASE = 0,
    MEDIUS_ACTION_PRESS = 1,
    MEDIUS_ACTION_FORCE_RELEASE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusAction MediusAction;
#else
typedef uint8_t MediusAction;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A mouse button. Values match the firmware button id.
enum MediusButton
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_BUTTON_LEFT = 0,
    MEDIUS_BUTTON_RIGHT = 1,
    MEDIUS_BUTTON_MIDDLE = 2,
    MEDIUS_BUTTON_SIDE1 = 3,
    MEDIUS_BUTTON_SIDE2 = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusButton MediusButton;
#else
typedef uint8_t MediusButton;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which axis/button a lock targets.
enum MediusLockTargetKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LOCK_TARGET_KIND_X = 0,
    MEDIUS_LOCK_TARGET_KIND_Y = 1,
    MEDIUS_LOCK_TARGET_KIND_WHEEL = 2,
    MEDIUS_LOCK_TARGET_KIND_BUTTON = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLockTargetKind MediusLockTargetKind;
#else
typedef uint8_t MediusLockTargetKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which edge of an axis/button a lock applies to.
enum MediusLockDirection
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LOCK_DIRECTION_BOTH = 0,
    MEDIUS_LOCK_DIRECTION_POSITIVE = 1,
    MEDIUS_LOCK_DIRECTION_NEGATIVE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLockDirection MediusLockDirection;
#else
typedef uint8_t MediusLockDirection;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A whole input class for a blanket lock.
enum MediusBlanket
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_BLANKET_KEYS = 0,
    MEDIUS_BLANKET_MEDIA = 1,
    MEDIUS_BLANKET_BUTTONS = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusBlanket MediusBlanket;
#else
typedef uint8_t MediusBlanket;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which status LED a command addresses.
enum MediusLedTarget
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LED_TARGET_DEVICE = 0,
    MEDIUS_LED_TARGET_HOST = 1,
    MEDIUS_LED_TARGET_BOTH = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLedTarget MediusLedTarget;
#else
typedef uint8_t MediusLedTarget;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// LED drive mode.
enum MediusLedMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LED_MODE_AUTO = 0,
    MEDIUS_LED_MODE_OFF = 1,
    MEDIUS_LED_MODE_SOLID = 2,
    MEDIUS_LED_MODE_BLINK = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLedMode MediusLedMode;
#else
typedef uint8_t MediusLedMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A reboot target chip + mode.
enum MediusRebootTarget
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_REBOOT_TARGET_DEVICE_DOWNLOAD = 0,
    MEDIUS_REBOOT_TARGET_HOST_DOWNLOAD = 1,
    MEDIUS_REBOOT_TARGET_DEVICE_RUN = 2,
    MEDIUS_REBOOT_TARGET_HOST_RUN = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusRebootTarget MediusRebootTarget;
#else
typedef uint8_t MediusRebootTarget;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What paces injected motion.
enum MediusEmitMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_EMIT_MODE_LEARNED = 0,
    MEDIUS_EMIT_MODE_INTERVAL = 1,
    MEDIUS_EMIT_MODE_FIXED = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusEmitMode MediusEmitMode;
#else
typedef uint8_t MediusEmitMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Which arm of a [`MediusCatchEvent`] is populated.
enum MediusCatchEventKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_CATCH_EVENT_KIND_MOUSE = 0,
    MEDIUS_CATCH_EVENT_KIND_KEYBOARD = 1,
    MEDIUS_CATCH_EVENT_KIND_MEDIA = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusCatchEventKind MediusCatchEventKind;
#else
typedef uint8_t MediusCatchEventKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A device log line's severity.
enum MediusLogLevel
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_LOG_LEVEL_ERROR = 0,
    MEDIUS_LOG_LEVEL_WARN = 1,
    MEDIUS_LOG_LEVEL_INFO = 2,
    MEDIUS_LOG_LEVEL_DEBUG = 3,
    MEDIUS_LOG_LEVEL_VERBOSE = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusLogLevel MediusLogLevel;
#else
typedef uint8_t MediusLogLevel;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A wire frame type (the `TYPE` byte). Used with the mock recorder.
enum MediusFrameType
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    MEDIUS_FRAME_TYPE_MOVE = 1,
    MEDIUS_FRAME_TYPE_INJECT = 3,
    MEDIUS_FRAME_TYPE_RESET = 4,
    MEDIUS_FRAME_TYPE_QUERY = 5,
    MEDIUS_FRAME_TYPE_RESP = 6,
    MEDIUS_FRAME_TYPE_REBOOT_DL = 7,
    MEDIUS_FRAME_TYPE_LOG = 8,
    MEDIUS_FRAME_TYPE_LED = 9,
    MEDIUS_FRAME_TYPE_LOCK = 10,
    MEDIUS_FRAME_TYPE_CATCH = 11,
    MEDIUS_FRAME_TYPE_MOUSE_EVENT = 12,
    MEDIUS_FRAME_TYPE_KB_EVENT = 15,
    MEDIUS_FRAME_TYPE_CONS_EVENT = 16,
    MEDIUS_FRAME_TYPE_OPTION = 17,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum MediusFrameType MediusFrameType;
#else
typedef uint8_t MediusFrameType;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// An open connection to one medius box. Opaque; create with `medius_device_open`/`_find`/`_with_mock`
// and release with `medius_device_free`.
typedef struct MediusDevice MediusDevice;

// A live CATCH event stream. Opaque; create with `medius_device_catch_events`, release with
// `medius_event_stream_free` (which unsubscribes when the last handle drops).
typedef struct MediusEventStream MediusEventStream;

// A device LOG stream. Opaque; create with `medius_device_logs`, release with `medius_log_stream_free`.
typedef struct MediusLogStream MediusLogStream;

#if defined(MEDIUS_FEATURE_MOCK)
// A scriptable fake box. Opaque; create with `medius_mock_new`, free with `medius_mock_free`.
// Cloning (via `medius_device_with_mock`) shares state, so a configured mock drives a real `Device`.
typedef struct MediusMockBox MediusMockBox;
#endif

// A discovered medius serial port. `path` is NUL-terminated.
typedef struct MediusPortInfo {
    char path[MEDIUS_MAX_PATH];
    uint16_t vid;
    uint16_t pid;
} MediusPortInfo;

// A relative-axis drive for `medius_device_move_axis`. For `Cursor`, `dx`/`dy` apply; for `Wheel`,
// `wheel` applies. Build with the `medius_motion_*` helpers.
typedef struct MediusMotion {
    MediusMotionKind kind;
    int16_t dx;
    int16_t dy;
    int16_t wheel;
} MediusMotion;

// A momentary usage for `medius_device_inject`. `value` holds the button id, key usage, or media
// usage depending on `kind`. Build with the `medius_input_*` helpers.
typedef struct MediusInput {
    MediusInputKind kind;
    uint16_t value;
} MediusInput;

// A keyboard key, addressed by HID Keyboard/Keypad usage. Modifiers are `0xE0..=0xE7`.
typedef uint8_t MediusKey;

// A media key, addressed by 16-bit HID Consumer usage.
typedef uint16_t MediusMediaKey;

// A lock target. `button` is meaningful only when `kind` is `Button`.
typedef struct MediusLockTarget {
    MediusLockTargetKind kind;
    MediusButton button;
} MediusLockTarget;

// Decoded firmware version.
typedef struct MediusVersion {
    uint8_t proto_ver;
    uint8_t fw_major;
    uint8_t fw_minor;
    uint8_t fw_patch;
} MediusVersion;

// Box health flags (each field is 0 or 1).
typedef struct MediusHealth {
    uint8_t link_up;
    uint8_t mouse_attached;
    uint8_t clone_configured;
    uint8_t injection_active;
    uint8_t rate_confident;
    uint8_t lock_on;
    uint8_t catch_on;
    uint8_t kbd_attached;
} MediusHealth;

// The cloned mouse's USB identity.
typedef struct MediusMouseInfo {
    uint16_t vid;
    uint16_t pid;
    uint16_t bcd_device;
    uint16_t bcd_usb;
    uint8_t has_serial;
    uint8_t has_bos;
} MediusMouseInfo;

// Mouse half of the cloned device's capabilities.
typedef struct MediusMouseCaps {
    uint8_t n_buttons;
    uint8_t has_x;
    uint8_t has_y;
    uint8_t has_wheel;
    uint8_t has_report_id;
    uint8_t n_hid;
} MediusMouseCaps;

// Keyboard half of the cloned device's capabilities. `n_keys == 0xFF` signals an NKRO bitmap.
typedef struct MediusKbdCaps {
    uint8_t n_keys;
    uint8_t nkro;
    uint8_t has_consumer;
    uint8_t has_system;
    uint8_t has_report_id;
} MediusKbdCaps;

// The whole cloned device's capabilities.
typedef struct MediusCaps {
    struct MediusMouseCaps mouse;
    struct MediusKbdCaps keyboard;
    uint8_t mouse_change_driven;
    uint8_t kbd_change_driven;
} MediusCaps;

// The live native report rate and clone poll period.
typedef struct MediusRate {
    uint16_t native_period_us;
    uint16_t poll_period_us;
    uint8_t confident;
    uint8_t change_driven;
} MediusRate;

// Box-side delivery/telemetry counters.
typedef struct MediusStats {
    uint32_t inject_emits;
    uint16_t tx_drops;
    uint16_t tx_merges;
    uint8_t tx_maxdepth;
    uint8_t tx_wedges;
    uint16_t wakeups;
    uint16_t reset_count;
    uint16_t config_count;
} MediusStats;

// The active lock bitmask. Use `medius_locks_is_locked` to test a target/direction.
typedef struct MediusLocks {
    uint16_t mask;
} MediusLocks;

// The active catch subscription mask plus the box-side dropped-event count.
typedef struct MediusCatchState {
    uint8_t mask;
    uint32_t dropped;
} MediusCatchState;

// Imperfect-clone opt-in and over-capacity status (each field is 0 or 1).
typedef struct MediusImperfectStatus {
    uint8_t allowed;
    uint8_t over_capacity;
    uint8_t clone_imperfect;
} MediusImperfectStatus;

// Emit-rate pacing mode plus the rate in effect. `fixed_hz` is the rate requested for `Fixed` (0
// otherwise); `resolved_hz` is the ceiling actually in effect (0 = learnt/adaptive).
typedef struct MediusEmitPaceStatus {
    MediusEmitMode mode;
    uint16_t fixed_hz;
    uint16_t resolved_hz;
} MediusEmitPaceStatus;

// Host-side always-on counters.
typedef struct MediusCountersSnapshot {
    uint64_t frames_tx;
    uint64_t frames_rx;
    uint64_t crc_drops;
    uint64_t reconnects;
} MediusCountersSnapshot;

// One physical mouse report. `buttons` is a bitmask by button id.
typedef struct MediusMouseEvent {
    uint8_t buttons;
    int16_t dx;
    int16_t dy;
    int16_t wheel;
} MediusMouseEvent;

// One physical keyboard snapshot: a modifier bitmap plus the pressed non-modifier keycodes in
// `keys[0..n_keys]`.
typedef struct MediusKeyboardEvent {
    uint8_t modifiers;
    uint8_t n_keys;
    uint8_t keys[MEDIUS_MAX_KEYS];
} MediusKeyboardEvent;

// One physical media snapshot: the active Consumer usages in `keys[0..n_keys]`.
typedef struct MediusMediaEvent {
    uint8_t n_keys;
    uint16_t keys[MEDIUS_MAX_MEDIA_KEYS];
} MediusMediaEvent;

// A CATCH subscription mask, an OR of the `MEDIUS_CATCH_MASK_*` bits.
typedef uint8_t MediusCatchMask;

// The populated arm of a [`MediusCatchEvent`]; read the field matching the event's `kind`.
typedef union MediusCatchEventData {
    struct MediusMouseEvent mouse;
    struct MediusKeyboardEvent keyboard;
    struct MediusMediaEvent media;
} MediusCatchEventData;

// One catch-stream event. Read `data.mouse` / `data.keyboard` / `data.media` per `kind`.
typedef struct MediusCatchEvent {
    MediusCatchEventKind kind;
    union MediusCatchEventData data;
} MediusCatchEvent;

// One device log line. `text` is NUL-terminated.
typedef struct MediusLogLine {
    MediusLogLevel level;
    char text[MEDIUS_MAX_LOG_TEXT];
} MediusLogLine;

#define MEDIUS_KEY_A 4

#define MEDIUS_KEY_B 5

#define MEDIUS_KEY_C 6

#define MEDIUS_KEY_D 7

#define MEDIUS_KEY_E 8

#define MEDIUS_KEY_F 9

#define MEDIUS_KEY_G 10

#define MEDIUS_KEY_H 11

#define MEDIUS_KEY_I 12

#define MEDIUS_KEY_J 13

#define MEDIUS_KEY_K 14

#define MEDIUS_KEY_L 15

#define MEDIUS_KEY_M 16

#define MEDIUS_KEY_N 17

#define MEDIUS_KEY_O 18

#define MEDIUS_KEY_P 19

#define MEDIUS_KEY_Q 20

#define MEDIUS_KEY_R 21

#define MEDIUS_KEY_S 22

#define MEDIUS_KEY_T 23

#define MEDIUS_KEY_U 24

#define MEDIUS_KEY_V 25

#define MEDIUS_KEY_W 26

#define MEDIUS_KEY_X 27

#define MEDIUS_KEY_Y 28

#define MEDIUS_KEY_Z 29

#define MEDIUS_KEY_1 30

#define MEDIUS_KEY_2 31

#define MEDIUS_KEY_3 32

#define MEDIUS_KEY_4 33

#define MEDIUS_KEY_5 34

#define MEDIUS_KEY_6 35

#define MEDIUS_KEY_7 36

#define MEDIUS_KEY_8 37

#define MEDIUS_KEY_9 38

#define MEDIUS_KEY_0 39

#define MEDIUS_KEY_ENTER 40

#define MEDIUS_KEY_ESCAPE 41

#define MEDIUS_KEY_BACKSPACE 42

#define MEDIUS_KEY_TAB 43

#define MEDIUS_KEY_SPACE 44

#define MEDIUS_KEY_CAPS_LOCK 57

#define MEDIUS_KEY_INSERT 73

#define MEDIUS_KEY_HOME 74

#define MEDIUS_KEY_PAGE_UP 75

#define MEDIUS_KEY_DELETE 76

#define MEDIUS_KEY_END 77

#define MEDIUS_KEY_PAGE_DOWN 78

#define MEDIUS_KEY_RIGHT 79

#define MEDIUS_KEY_LEFT 80

#define MEDIUS_KEY_DOWN 81

#define MEDIUS_KEY_UP 82

#define MEDIUS_KEY_F1 58

#define MEDIUS_KEY_F2 59

#define MEDIUS_KEY_F3 60

#define MEDIUS_KEY_F4 61

#define MEDIUS_KEY_F5 62

#define MEDIUS_KEY_F6 63

#define MEDIUS_KEY_F7 64

#define MEDIUS_KEY_F8 65

#define MEDIUS_KEY_F9 66

#define MEDIUS_KEY_F10 67

#define MEDIUS_KEY_F11 68

#define MEDIUS_KEY_F12 69

#define MEDIUS_KEY_LEFT_CTRL 224

#define MEDIUS_KEY_LEFT_SHIFT 225

#define MEDIUS_KEY_LEFT_ALT 226

#define MEDIUS_KEY_LEFT_GUI 227

#define MEDIUS_KEY_RIGHT_CTRL 228

#define MEDIUS_KEY_RIGHT_SHIFT 229

#define MEDIUS_KEY_RIGHT_ALT 230

#define MEDIUS_KEY_RIGHT_GUI 231

#define MEDIUS_MEDIA_PLAY_PAUSE 205

#define MEDIUS_MEDIA_STOP 183

#define MEDIUS_MEDIA_NEXT_TRACK 181

#define MEDIUS_MEDIA_PREV_TRACK 182

#define MEDIUS_MEDIA_MUTE 226

#define MEDIUS_MEDIA_VOLUME_UP 233

#define MEDIUS_MEDIA_VOLUME_DOWN 234

#define MEDIUS_MEDIA_PLAY 176

#define MEDIUS_MEDIA_PAUSE 177

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Open the box at serial `path` (a NUL-terminated UTF-8 string), handshake, and write the handle to
// `*out`. The caller owns the handle and must free it with `medius_device_free`.
MediusStatus medius_device_open(const char *path, struct MediusDevice **out);

// Discover the first medius box by USB id, open it, handshake, and write the handle to `*out`.
MediusStatus medius_device_find(struct MediusDevice **out);

// Clone a device handle: another owner of the same underlying connection (the link is shared and
// reference-counted, like `Device::clone` in Rust). Each clone must be freed. Null in -> null out.
struct MediusDevice *medius_device_clone(const struct MediusDevice *dev);

// Free a device handle (joins the background reader/keepalive threads when the last clone drops).
// Null is a no-op.
void medius_device_free(struct MediusDevice *dev);

// Enumerate medius serial ports into `out` (up to `cap`). Writes the total found to `*out_total`
// (may exceed `cap`) and returns the number written. Ports with an unrepresentable path are omitted.
uintptr_t medius_find_ports(struct MediusPortInfo *out,
                            uintptr_t cap,
                            uintptr_t *out_total);

MediusStatus medius_device_move_rel(struct MediusDevice *dev, int16_t dx, int16_t dy);

MediusStatus medius_device_wheel(struct MediusDevice *dev, int16_t delta);

MediusStatus medius_device_move_axis(struct MediusDevice *dev, struct MediusMotion motion);

MediusStatus medius_device_inject(struct MediusDevice *dev,
                                  struct MediusInput input,
                                  MediusAction action);

MediusStatus medius_device_button(struct MediusDevice *dev,
                                  MediusButton button,
                                  MediusAction action);

MediusStatus medius_device_press(struct MediusDevice *dev, MediusButton button);

MediusStatus medius_device_soft_release(struct MediusDevice *dev, MediusButton button);

MediusStatus medius_device_force_release(struct MediusDevice *dev, MediusButton button);

MediusStatus medius_device_key(struct MediusDevice *dev, MediusKey key, MediusAction action);

MediusStatus medius_device_key_down(struct MediusDevice *dev, MediusKey key);

MediusStatus medius_device_key_up(struct MediusDevice *dev, MediusKey key);

MediusStatus medius_device_key_force_release(struct MediusDevice *dev, MediusKey key);

MediusStatus medius_device_media(struct MediusDevice *dev,
                                 MediusMediaKey media,
                                 MediusAction action);

MediusStatus medius_device_media_down(struct MediusDevice *dev, MediusMediaKey media);

MediusStatus medius_device_media_up(struct MediusDevice *dev, MediusMediaKey media);

MediusStatus medius_device_media_force_release(struct MediusDevice *dev, MediusMediaKey media);

MediusStatus medius_device_lock(struct MediusDevice *dev,
                                struct MediusLockTarget target,
                                MediusLockDirection dir);

MediusStatus medius_device_unlock(struct MediusDevice *dev,
                                  struct MediusLockTarget target,
                                  MediusLockDirection dir);

MediusStatus medius_device_lock_key(struct MediusDevice *dev,
                                    MediusKey key,
                                    MediusLockDirection dir);

MediusStatus medius_device_unlock_key(struct MediusDevice *dev,
                                      MediusKey key,
                                      MediusLockDirection dir);

MediusStatus medius_device_lock_media(struct MediusDevice *dev, MediusMediaKey media);

MediusStatus medius_device_unlock_media(struct MediusDevice *dev, MediusMediaKey media);

MediusStatus medius_device_lock_all(struct MediusDevice *dev, MediusBlanket what);

MediusStatus medius_device_unlock_all(struct MediusDevice *dev, MediusBlanket what);

MediusStatus medius_device_led(struct MediusDevice *dev,
                               MediusLedTarget target,
                               MediusLedMode mode,
                               uint8_t level);

MediusStatus medius_device_reset(struct MediusDevice *dev);

MediusStatus medius_device_reapply(struct MediusDevice *dev);

MediusStatus medius_device_reconnect(struct MediusDevice *dev);

MediusStatus medius_device_reboot(struct MediusDevice *dev, MediusRebootTarget target);

MediusStatus medius_device_allow_imperfect_clones(struct MediusDevice *dev, bool allow);

// Set movement riding. When `enabled` is false the window is cleared (off); otherwise the injected
// motion rides a native cursor report seen within `window_ms` (rounded to whole ms by the firmware).
MediusStatus medius_device_set_movement_riding(struct MediusDevice *dev,
                                               bool enabled,
                                               uint32_t window_ms);

// Set what paces injected motion. `hz` is the target rate for `Fixed` (snapped to `1000/n`, capped
// 1 kHz); it is ignored for `Learned` and `Interval`.
MediusStatus medius_device_set_emit_pace(struct MediusDevice *dev,
                                         MediusEmitMode mode,
                                         uint16_t hz);

MediusStatus medius_device_query_version(struct MediusDevice *dev, struct MediusVersion *out);

MediusStatus medius_device_query_health(struct MediusDevice *dev, struct MediusHealth *out);

MediusStatus medius_device_query_mouse_info(struct MediusDevice *dev, struct MediusMouseInfo *out);

MediusStatus medius_device_caps(struct MediusDevice *dev, struct MediusCaps *out);

MediusStatus medius_device_query_rate(struct MediusDevice *dev, struct MediusRate *out);

MediusStatus medius_device_query_stats(struct MediusDevice *dev, struct MediusStats *out);

MediusStatus medius_device_query_locks(struct MediusDevice *dev, struct MediusLocks *out);

MediusStatus medius_device_query_catch(struct MediusDevice *dev, struct MediusCatchState *out);

MediusStatus medius_device_query_imperfect(struct MediusDevice *dev,
                                           struct MediusImperfectStatus *out);

// Query the movement-riding window. Writes whether it is on to `*out_enabled` and, when on, the
// window in whole ms to `*out_window_ms` (0 when off).
MediusStatus medius_device_query_movement_riding(struct MediusDevice *dev,
                                                 bool *out_enabled,
                                                 uint32_t *out_window_ms);

MediusStatus medius_device_query_emit_pace(struct MediusDevice *dev,
                                           struct MediusEmitPaceStatus *out);

MediusStatus medius_device_counters(struct MediusDevice *dev, struct MediusCountersSnapshot *out);

// Default RESP wait before a query times out, in milliseconds.
uint32_t medius_default_query_timeout_ms(void);

// Default keepalive cadence for held overrides, in milliseconds.
uint32_t medius_default_keepalive_cadence_ms(void);

// The C ABI version. Bumped on any breaking change to this header.
uint32_t medius_abi_version(void);

// The medius-capi crate version as a static NUL-terminated string.
const char *medius_version_string(void);

// Copy the last error's display text into `buf` (NUL-terminated, truncated to `cap`). Returns the
// full message length in bytes, excluding the NUL, so a caller can size a buffer and retry.
uintptr_t medius_last_error_message(char *buf, uintptr_t cap);

// The `BadProtoVer` version byte from the last error, or 0 if the last error carried none.
uint8_t medius_last_error_proto_ver(void);

// Build an [`MediusInput`] addressing a mouse button.
struct MediusInput medius_input_button(MediusButton button);

// Build an [`MediusInput`] addressing a keyboard key.
struct MediusInput medius_input_key(MediusKey key);

// Build an [`MediusInput`] addressing a media key.
struct MediusInput medius_input_media(MediusMediaKey media);

// Build a cursor-motion [`MediusMotion`].
struct MediusMotion medius_motion_cursor(int16_t dx, int16_t dy);

// Build a wheel [`MediusMotion`].
struct MediusMotion medius_motion_wheel(int16_t delta);

// Whether `target`/`dir` is locked in `locks` (`Both` requires both edges). Mirrors
// `medius::Locks::is_locked`; `Locks` has no public constructor, so the bit logic is replicated here.
bool medius_locks_is_locked(struct MediusLocks locks,
                            struct MediusLockTarget target,
                            MediusLockDirection dir);

// The native report rate in Hz, written to `out_hz`. Returns false (and leaves `out_hz` untouched)
// when there is no continuous cadence. Delegates to `medius::Rate::native_hz`.
bool medius_rate_native_hz(struct MediusRate rate, float *out_hz);

// Whether `button` is held in a mouse snapshot. Delegates to `medius::MouseEvent::is_pressed`.
bool medius_mouse_event_is_pressed(const struct MediusMouseEvent *event, MediusButton button);

// Whether `key` is held in a keyboard snapshot (modifier from the bitmap, else searched in the
// keycode list). Mirrors `medius::KeyboardEvent::is_pressed` without allocating.
bool medius_keyboard_event_is_pressed(const struct MediusKeyboardEvent *event, MediusKey key);

// Whether `media` is active in a media snapshot. Mirrors `medius::MediaEvent::is_pressed`.
bool medius_media_event_is_pressed(const struct MediusMediaEvent *event, MediusMediaKey media);

// Whether a mouse interface is bound. Delegates to `medius::Caps::has_mouse`.
bool medius_caps_has_mouse(struct MediusCaps caps);

// Whether a keyboard interface is bound. Delegates to `medius::Caps::has_keyboard`.
bool medius_caps_has_keyboard(struct MediusCaps caps);

// Whether the clone is composite (multi-HID-interface). Delegates to `medius::Caps::is_composite`.
bool medius_caps_is_composite(struct MediusCaps caps);

// Subscribe to the physical-input event stream for the given class `mask` (the `MEDIUS_CATCH_MASK_*`
// bits). Writes the stream handle to `*out`.
MediusStatus medius_device_catch_events(struct MediusDevice *dev,
                                        MediusCatchMask mask,
                                        struct MediusEventStream **out);

// Clone an event-stream handle: another handle to the SAME subscription (shared queue, like
// `EventStream::clone` in Rust). The subscription ends when the last clone is freed. Null in -> null out.
struct MediusEventStream *medius_event_stream_clone(const struct MediusEventStream *stream);

// Free an event-stream handle. Null is a no-op.
void medius_event_stream_free(struct MediusEventStream *stream);

// Block until the next physical-input event, writing it to `*out`. Returns `ErrDisconnected` when the
// stream closes (after reset or link loss).
MediusStatus medius_event_stream_recv(struct MediusEventStream *stream,
                                      struct MediusCatchEvent *out);

// The next buffered event, written to `*out`; returns false if none is queued (never blocks).
bool medius_event_stream_try_recv(struct MediusEventStream *stream, struct MediusCatchEvent *out);

// Block up to `timeout_ms` for the next event, written to `*out`; returns false on timeout or close.
bool medius_event_stream_recv_timeout(struct MediusEventStream *stream,
                                      uint64_t timeout_ms,
                                      struct MediusCatchEvent *out);

// Events this stream dropped because the consumer fell behind (host-side back-pressure).
uint64_t medius_event_stream_dropped(struct MediusEventStream *stream);

// Open the device LOG stream, writing the handle to `*out`.
MediusStatus medius_device_logs(struct MediusDevice *dev, struct MediusLogStream **out);

// Clone a log-stream handle: another handle to the same LOG channel. Null in -> null out.
struct MediusLogStream *medius_log_stream_clone(const struct MediusLogStream *stream);

// Free a log-stream handle. Null is a no-op.
void medius_log_stream_free(struct MediusLogStream *stream);

// Block until the next LOG line, writing it to `*out`. Returns `ErrDisconnected` on close.
MediusStatus medius_log_stream_recv(struct MediusLogStream *stream, struct MediusLogLine *out);

// The next buffered LOG line, written to `*out`; returns false if none is queued (never blocks).
bool medius_log_stream_try_recv(struct MediusLogStream *stream, struct MediusLogLine *out);

// Block up to `timeout_ms` for the next LOG line, written to `*out`; false on timeout or close.
bool medius_log_stream_recv_timeout(struct MediusLogStream *stream,
                                    uint64_t timeout_ms,
                                    struct MediusLogLine *out);

#if defined(MEDIUS_FEATURE_FLASH)
// Reboot a chip to ROM download and flash `bin_path` via esptool on PATH. `host` selects the host
// chip (otherwise the device chip). Blocking (~2 s settle + subprocess). Platform-gated to Linux and
// Windows; returns `ErrUnknown` elsewhere.
MediusStatus medius_flash(const char *port,
                          const char *bin_path,
                          bool host);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Create a fresh mock that records commands and auto-answers queries with defaults.
struct MediusMockBox *medius_mock_new(void);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Clone a mock handle: another handle sharing the same recorded state (like `MockBox::clone`).
// Null in -> null out.
struct MediusMockBox *medius_mock_clone(const struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Free a mock handle. Null is a no-op.
void medius_mock_free(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the version the mock answers to a VERSION query.
void medius_mock_set_version(struct MediusMockBox *mock, struct MediusVersion value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the health flags the mock answers to a HEALTH query.
void medius_mock_set_health(struct MediusMockBox *mock, struct MediusHealth value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the mouse identity the mock answers to a MOUSE_INFO query.
void medius_mock_set_mouse_info(struct MediusMockBox *mock, struct MediusMouseInfo value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the whole capabilities (mouse + keyboard) the mock answers to a CAPS query.
void medius_mock_set_caps(struct MediusMockBox *mock, struct MediusCaps value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set only the mouse half of the capabilities.
void medius_mock_set_mouse_caps(struct MediusMockBox *mock, struct MediusMouseCaps value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set only the keyboard half of the capabilities (and mark the keyboard class change-driven).
void medius_mock_set_kbd_caps(struct MediusMockBox *mock, struct MediusKbdCaps value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the rate the mock answers to a RATE query.
void medius_mock_set_rate(struct MediusMockBox *mock, struct MediusRate value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the stats the mock answers to a STATS query.
void medius_mock_set_stats(struct MediusMockBox *mock, struct MediusStats value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the lock bitmask the mock answers to a LOCKS query.
void medius_mock_set_locks(struct MediusMockBox *mock, struct MediusLocks value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the catch state the mock answers to a CATCH query.
void medius_mock_set_catch_state(struct MediusMockBox *mock, struct MediusCatchState value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the imperfect-clone status the mock answers to an OPTION(IMPERFECT) query.
void medius_mock_set_imperfect_status(struct MediusMockBox *mock,
                                      struct MediusImperfectStatus value);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the movement-riding window the mock answers to a query; `enabled == false` means off.
void medius_mock_set_movement_riding(struct MediusMockBox *mock, bool enabled, uint32_t window_ms);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Set the emit-rate pacing mode the mock answers to an OPTION(EMIT) query; `hz` matters only for
// `Fixed`.
void medius_mock_set_emit_pace(struct MediusMockBox *mock, MediusEmitMode mode, uint16_t hz);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Make the mock unresponsive to queries (it still records commands). One-way, for testing timeouts.
void medius_mock_silent(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Inject raw bytes into the host's inbound stream, as if the box put them on the wire.
void medius_mock_push_raw(struct MediusMockBox *mock, const uint8_t *bytes, uintptr_t len);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a LOG line as if the box emitted it (surfaces on the device's log stream).
void medius_mock_push_log(struct MediusMockBox *mock, MediusLogLevel level, const char *text);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a MOUSE_EVENT as if the box emitted it (surfaces as a `Mouse` catch event).
void medius_mock_push_event(struct MediusMockBox *mock,
                            uint8_t seq,
                            struct MediusMouseEvent report);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a KB_EVENT as if the box emitted it (surfaces as a `Keyboard` catch event).
void medius_mock_push_kb_event(struct MediusMockBox *mock,
                               uint8_t seq,
                               const struct MediusKeyboardEvent *event);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Push a CONS_EVENT as if the box emitted it (surfaces as a `Media` catch event).
void medius_mock_push_cons_event(struct MediusMockBox *mock,
                                 uint8_t seq,
                                 const struct MediusMediaEvent *event);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// The number of commands the host has sent to the mock so far.
uintptr_t medius_mock_recorded(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Whether the host has sent at least one frame of the given type.
bool medius_mock_saw(struct MediusMockBox *mock, MediusFrameType ty);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Clear the recorded-command log.
void medius_mock_clear_recorded(struct MediusMockBox *mock);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Read recorded frame `idx`: its type to `*out_ty`, its SEQ to `*out_seq`, and up to `cap` payload
// bytes to `payload_buf`. Returns the full payload length (may exceed `cap`), or 0 if `idx` is out
// of range. Out-pointers may be null to skip them.
uintptr_t medius_mock_recorded_frame(struct MediusMockBox *mock,
                                     uintptr_t idx,
                                     MediusFrameType *out_ty,
                                     uint8_t *out_seq,
                                     uint8_t *payload_buf,
                                     uintptr_t cap);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Build a `Device` over the mock WITHOUT a handshake (clones the mock's shared state).
MediusStatus medius_device_with_mock(const struct MediusMockBox *mock, struct MediusDevice **out);
#endif

#if defined(MEDIUS_FEATURE_MOCK)
// Build a `Device` over the mock AND run the version handshake (can fail if the mock is silent).
MediusStatus medius_device_open_mock(const struct MediusMockBox *mock, struct MediusDevice **out);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MEDIUS_H */
